In [1]:
!pip3 install gensim

In [2]:
# Library gensim
import gensim
from gensim.models import FastText
from gensim.models import TfidfModel
from gensim.corpora import Dictionary


import pandas as pd 
import numpy as np
import nltk
from tqdm.auto import tqdm

from nltk.tokenize import word_tokenize
from gensim.models import FastText

import os 
working_directory = os.getcwd()
print(working_directory)

C:\Users\Asus\BISMILLAH TA SUKMA


# FastText Corpus Twitter

In [3]:
df_twt = pd.read_csv(r"prepTwitter.csv", usecols=['Clean Text'])

In [4]:
df_twt.rename(columns = {'Clean Text':'clean_text'}, inplace = True)
df_twt

clean_text
0      handphone lapor wajib bantu lacak imei perihal...
1      tidak tahu telkomsel lambat kuota promo murah ...
2                               kendala sinyal telkomsel
3      tidak bisa nomor mati dihidupakan grapari nomo...
4      admin kemarin aplikasi punya telkomsel ganggu ...
...                                                  ...
17214  sinyal minus tolong baik problem location cama...
17215            punya telkomsel ganggu aduh desak pakai
17216               allah tambah kerja esuk neng grapari
17217  admin sinyal telkomsel rumah daerah rawabunga ...
17218  tante kirim pakai nomor telkomsel langsung gra...

[17219 rows x 1 columns]

In [5]:
df_twt['clean_text'] = df_twt['clean_text'].apply(str)
df_twt['clean_text'] = df_twt['clean_text'].astype(np.uint8,errors='ignore')

In [6]:
def tokenizing(data):
    return nltk.tokenize.word_tokenize(data)

In [7]:
df_twt['clean_text'] = df_twt['clean_text'].apply(tokenizing)
df_twt

clean_text
0      [handphone, lapor, wajib, bantu, lacak, imei, ...
1      [tidak, tahu, telkomsel, lambat, kuota, promo,...
2                           [kendala, sinyal, telkomsel]
3      [tidak, bisa, nomor, mati, dihidupakan, grapar...
4      [admin, kemarin, aplikasi, punya, telkomsel, g...
...                                                  ...
17214  [sinyal, minus, tolong, baik, problem, locatio...
17215     [punya, telkomsel, ganggu, aduh, desak, pakai]
17216        [allah, tambah, kerja, esuk, neng, grapari]
17217  [admin, sinyal, telkomsel, rumah, daerah, rawa...
17218  [tante, kirim, pakai, nomor, telkomsel, langsu...

[17219 rows x 1 columns]

In [8]:
model_twt= FastText(sentences = df_twt['clean_text'], window = 5, min_count = 3, workers = 4, sg = 0, hs = 0)

In [9]:
model_twt.save('model_twitter')

#### Save Model FastText Twitter

In [10]:
os.makedirs("model_twt/fasttext/", exist_ok=True)

In [11]:
model_twt.save("model_twt/fasttext/prepTwitter.fasttext")

In [67]:
model_twt = FastText.load("model_twt/fasttext/prepTwitter.fasttext")

#### Model Information

In [14]:
ft_twt = model_twt.wv

In [15]:
ft_twt.vectors

array([[-0.6703734 ,  0.13236398,  0.08674868, ...,  0.18124846,
         0.14732136,  0.6538749 ],
       [-0.68819356,  0.46446002,  0.15979293, ...,  0.58091205,
         0.0992934 ,  0.73994756],
       [-0.5078082 , -0.20717657,  0.41770163, ...,  0.39577445,
        -0.3268645 ,  0.37631133],
       ...,
       [-0.54079926, -0.00761004,  0.2445055 , ...,  0.2571397 ,
        -0.01352031,  0.56788045],
       [-0.35028046, -0.01133135,  0.17638233, ...,  0.20392492,
        -0.05066896,  0.3443741 ],
       [-0.34909466, -0.02007227,  0.17432006, ...,  0.18656908,
        -0.03744285,  0.35147098]], dtype=float32)

In [16]:
# coba 
ft_twt["jlek"]

array([-0.3212564 ,  0.10409523,  0.08990949,  0.07296191,  0.3628002 ,
        0.10916419,  0.11657152,  0.04950202,  0.27293742,  0.17547649,
       -0.35771725, -0.11334901, -0.2899717 , -0.03733845,  0.00334315,
       -0.14789246,  0.2882373 , -0.04996614, -0.15397082, -0.2230863 ,
        0.09249818,  0.03782368, -0.01233696,  0.1512796 , -0.37225476,
       -0.11393103, -0.12623762,  0.02946741,  0.08972017,  0.20532589,
        0.03862533,  0.13783094, -0.10082572, -0.22794141,  0.09875405,
        0.03835576,  0.36984208, -0.086599  , -0.12701716, -0.4691242 ,
       -0.08534567, -0.30329084, -0.02113611, -0.19436249, -0.19661275,
        0.15368515, -0.12272346, -0.18566896,  0.14529394,  0.11991102,
       -0.01591241,  0.03126287, -0.00115914,  0.48697272, -0.4104648 ,
       -0.12860757,  0.02413506,  0.00605895,  0.1139949 , -0.29304266,
        0.06448582,  0.13531   , -0.3707388 ,  0.05374656,  0.02254109,
        0.20733391,  0.304172  ,  0.1043461 , -0.04883746,  0.41

### Sanity Check

In [12]:
# Train Similarity Model FastText
ft_twt.most_similar('admin')

NameError: name 'ft_twt' is not defined

In [19]:
def word_similarity(text):
    x = []
    for i in text:
        x.append(i[0])
    return x

def create_corpus10(text):
    word = ft_twt.most_similar(text, topn=10)
    return word

words10 = ft_twt.key_to_index

corpus10 = list(map(create_corpus10, words10))
cft10 = pd.DataFrame(corpus10, index=words10)
cft10['All'] = corpus10
cft10['similarity'] = cft10['All'].apply(word_similarity)

cft10.to_excel('corpus_tweet.xlsx')

In [20]:
cft10

0  \
telkomsel    (telkomselku, 0.9984503388404846)   
sinyal             (lampu, 0.9950275421142578)   
grapari             (urus, 0.9989123940467834)   
jaring         (jaringane, 0.9965177178382874)   
lambat             (jeleq, 0.9980224370956421)   
...                                        ...   
diupgrade          (bantu, 0.9991438984870911)   
tulungagung      (tanjung, 0.9998350143432617)   
mek                (memek, 0.9998995065689087)   
karyawannya        (mesti, 0.9998033046722412)   
gocar               (luar, 0.9998671412467957)   

                                               1  \
telkomsel    (telkomselindo, 0.9951608180999756)   
sinyal              (jaring, 0.9920701384544373)   
grapari              (ganti, 0.9951496720314026)   
jaring               (hujan, 0.9962073564529419)   
lambat               (jelek, 0.9979934692382812)   
...                                          ...   
diupgrade            (tentu, 0.9990853667259216)   
tulungagung          (dusun, 0.9997427463531494)   
mek                 (mental, 0.9998929500579834)   
karyawannya       (karakter, 0.9997987747192383)   
gocar                 (aman, 0.9998283982276917)   

                                           2  \
telkomsel       (telkoms, 0.995059609413147)   
sinyal          (jelekk, 0.9903920888900757)   
grapari          (kartu, 0.9935681819915771)   
jaring          (baguss, 0.9941701889038086)   
lambat         (jelekkk, 0.9979405403137207)   
...                                      ...   
diupgrade         (suru, 0.9990837574005127)   
tulungagung  (manggarai, 0.9997299909591675)   
mek               (giga, 0.9998365044593811)   
karyawannya         (ur, 0.9996851682662964)   
gocar        (dibenahin, 0.9997789859771729)   

                                                   3  \
telkomsel    (indihometelkomsel, 0.9926912784576416)   
sinyal                  (listrik, 0.989945113658905)   
grapari                  (nomer, 0.9894883036613464)   
jaring                  (jelekkk, 0.994096040725708)   
lambat                   (jelekk, 0.997814416885376)   
...                                              ...   
diupgrade                (henti, 0.9988859295845032)   
tulungagung              (lantai, 0.999701976776123)   
mek                    (kecuali, 0.9998307824134827)   
karyawannya             (merger, 0.9996351003646851)   
gocar                     (hong, 0.9997757077217102)   

                                              4  \
telkomsel    (telkomselnya, 0.9903486371040344)   
sinyal            (jelekkk, 0.9896805882453918)   
grapari         (kartuhalo, 0.9890449047088623)   
jaring              (mampu, 0.9938648343086243)   
lambat              (rumah, 0.9967043399810791)   
...                                         ...   
diupgrade           (virus, 0.9987457394599915)   
tulungagung       (sambung, 0.9996565580368042)   
mek               (optimal, 0.9998061060905457)   
karyawannya          (solo, 0.9996349811553955)   
gocar               (tahan, 0.9997467398643494)   

                                            5  \
telkomsel    (telkomshit, 0.9897422790527344)   
sinyal             (hujan, 0.987775444984436)   
grapari            (krtu, 0.9886213541030884)   
jaring           (daerah, 0.9936137199401855)   
lambat           (daerah, 0.9959631562232971)   
...                                       ...   
diupgrade         (teman, 0.9986934065818787)   
tulungagung      (mulung, 0.9995965957641602)   
mek             (official, 0.999801516532898)   
karyawannya      (negeri, 0.9996225237846375)   
gocar             (iseng, 0.9997342228889465)   

                                            6  \
telkomsel      (tekomsel, 0.9895142316818237)   
sinyal            (mampu, 0.9860238432884216)   
grapari             (ktp, 0.9878056645393372)   
jaring          (listrik, 0.9933779239654541)   
lambat         (indihome, 0.9933636784553528)   
...                                       ...   
diupgrade         (suruh

## FastText Corpus Berita

In [34]:
df_news = pd.read_csv(r"preproBerita.csv", usecols=['Clean Text'])
df_news.rename(columns = {'Clean Text':'clean_text'}, inplace = True)
df_news

clean_text
0       jakarta badan pengawas pemilu dki jakarta menu...
1       jakarta wakil ketua komisi ix dpr saleh partao...
2       jakarta pasangan calon nomor urut tiga anies b...
3       jakarta rumah partai golkar sedikit terguncang...
4       jakarta calon wakil gubernur sandiaga uno memi...
...                                                   ...
142539  tuhan menciptakan bangsa untuk maju melawan ke...
142540  apapun yang dapat anda lakukan atau impikan mu...
142541  perjuangan sejati bukan dinilai saat kita memu...
142542  banyak hal yang bisa menjatuhkanmu tapi satu n...
142543  orang yang suka berkata jujur akan mendapatkan...

[142544 rows x 1 columns]

In [38]:
df_news['clean_text'] = df_news['clean_text'].apply(str)
df_news['clean_text'] = df_news['clean_text'].astype(np.uint8,errors='ignore')

In [39]:
def tokenizing(data):
    return nltk.tokenize.word_tokenize(data)

df_news['clean_text'] = df_news['clean_text'].apply(tokenizing)
df_news

clean_text
0       [[, 'jakarta, ', ,, 'badan, ', ,, 'pengawas, '...
1       [[, 'jakarta, ', ,, 'wakil, ', ,, 'ketua, ', ,...
2       [[, 'jakarta, ', ,, 'pasangan, ', ,, 'calon, '...
3       [[, 'jakarta, ', ,, 'rumah, ', ,, 'partai, ', ...
4       [[, 'jakarta, ', ,, 'calon, ', ,, 'wakil, ', ,...
...                                                   ...
142539  [[, 'tuhan, ', ,, 'menciptakan, ', ,, 'bangsa,...
142540  [[, 'apapun, ', ,, 'yang, ', ,, 'dapat, ', ,, ...
142541  [[, 'perjuangan, ', ,, 'sejati, ', ,, 'bukan, ...
142542  [[, 'banyak, ', ,, 'hal, ', ,, 'yang, ', ,, 'b...
142543  [[, 'orang, ', ,, 'yang, ', ,, 'suka, ', ,, 'b...

[142544 rows x 1 columns]

In [40]:
model_news= FastText(sentences = df_news['clean_text'], window = 5, min_count = 3, workers = 4, sg = 0, hs = 0)

KeyboardInterrupt: 

In [24]:
model_news.save('model_berita')

In [134]:
os.makedirs("model_news/fasttext/", exist_ok=True)

In [137]:
model_news.save("model_news/fasttext/preproBerita.fasttext")

In [138]:
model_news = FastText.load("model_news/fasttext/preproBerita.fasttext")

In [25]:
ft_news = model_news.wv

In [26]:
ft_news.vectors

array([[ 3.64952952e-01, -2.23923326e-02,  7.23469257e-03, ...,
        -2.15563565e-01,  4.42710757e-01,  3.88677478e-01],
       [-1.78804025e-01,  3.05704147e-01,  6.77496195e-04, ...,
        -4.10624385e-01, -1.18622199e-01, -2.39721820e-01],
       [ 1.76299751e-01, -9.32980478e-02,  1.16015255e-01, ...,
         5.21947622e-01,  1.70865685e-01,  3.25058401e-01],
       ...,
       [-8.19343448e-01,  1.46656179e+00, -8.85602117e-01, ...,
         1.39385724e+00,  7.82845989e-02, -2.38896370e+00],
       [-1.35859561e+00,  1.83735025e+00,  1.73278183e-01, ...,
         8.00395191e-01,  4.99439418e-01, -3.31959009e+00],
       [-2.07930112e+00, -1.49702406e+00,  1.39644504e-01, ...,
        -4.04101193e-01,  2.40126371e+00, -9.94792640e-01]], dtype=float32)

In [27]:
# coba 
ft_news["kriminal"]

array([-1.8728288e-05, -2.2057125e-03,  9.8058232e-04,  9.9873194e-04,
       -5.9075397e-04,  2.0850869e-04,  6.6976924e-04,  5.3134200e-04,
        5.5313989e-04,  7.2020164e-04, -8.5915657e-05, -1.3695229e-03,
       -5.2517315e-04, -9.6428528e-04, -1.2074673e-03, -2.1964165e-03,
       -4.5806319e-05, -1.5432015e-03, -8.3113939e-04, -3.7443332e-04,
       -7.9568266e-04,  1.9328637e-03,  4.4132429e-04, -3.3157019e-04,
       -1.3698034e-03, -8.6837145e-04, -5.1717670e-04,  5.4012891e-04,
       -2.5146303e-03,  5.5549177e-04,  6.7247420e-05, -4.4193443e-05,
        1.1833658e-03,  9.3197782e-04,  9.5629506e-04, -6.5231754e-04,
        1.1269237e-03, -1.5869923e-04, -2.6108178e-03,  2.7011435e-03,
        5.9616385e-04, -6.1023084e-04, -9.8374637e-04,  6.6798925e-04,
       -2.0509250e-03,  4.6310114e-04, -1.1302645e-03,  1.1566996e-03,
       -5.3374050e-04,  9.5212826e-04,  1.1448096e-03, -1.2166220e-03,
       -4.3976228e-04,  2.4226298e-04,  1.3069883e-03,  1.6771853e-03,
      

In [31]:
# Train Similarity Model FastText
ft_news.most_similar('indonesia')

[('w', 0.12157713621854782),
 ('x', 0.09916957467794418),
 ('r', 0.08086537569761276),
 (' ', 0.0804147720336914),
 ('u', 0.07928096503019333),
 ('j', 0.07483448833227158),
 ('n', 0.054086845368146896),
 ('y', 0.031332600861787796),
 ('e', 0.027696147561073303),
 ('l', 0.014147326350212097)]

In [32]:
def word_similarity(text):
    x = []
    for i in text:
        x.append(i[0])
    return x

def create_corpus10(text):
    word = ft_news.most_similar(text, topn=10)
    return word

words10 = ft_news.key_to_index

corpus10 = list(map(create_corpus10, words10))
cfb10 = pd.DataFrame(corpus10, index=words10)
cfb10['All'] = corpus10
cfb10['similarity'] = cfb10['All'].apply(word_similarity)

cfb10.to_excel('corpus_berita.xlsx')

In [33]:
cfb10

0                         1  \
a   (u, 0.5754037499427795)   (g, 0.5576417446136475)   
   (q, 0.22765693068504333)    (n, 0.192879781126976)   
n  (a, 0.42743340134620667)  (g, 0.38037142157554626)   
i    (o, 0.368704229593277)   (r, 0.3140992522239685)   
e   (i, 0.2363346666097641)  (y, 0.21080224215984344)   
r   (l, 0.3455035388469696)   (i, 0.3140992224216461)   
t   (s, 0.4428796172142029)   (l, 0.4329518973827362)   
k    (g, 0.582477331161499)   (h, 0.5118564367294312)   
u     (a, 0.57540363073349)   (y, 0.4950939416885376)   
s  (d, 0.47148558497428894)     (l, 0.45655557513237)   
m   (g, 0.4890930950641632)   (t, 0.4247564971446991)   
d  (s, 0.47148558497428894)  (m, 0.39596396684646606)   
g   (y, 0.6339799761772156)   (k, 0.5824773907661438)   
p  (g, 0.42159056663513184)  (b, 0.40758413076400757)   
l   (s, 0.4565556049346924)   (t, 0.4329518973827362)   
b   (h, 0.5493905544281006)  (g, 0.48297736048698425)   
o   (v, 0.6923836469650269)   (c, 0.5981760025024414)   
h   (b, 0.5493905544281006)   (k, 0.5118563175201416)   
y   (g, 0.6339799761772156)  (u, 0.49509385228157043)   
j  (w, 0.45392146706581116)  (b, 0.44346392154693604)   
c   (o, 0.5981760025024414)   (x, 0.5699155330657959)   
w   (j, 0.4539214074611664)   (o, 0.2787022888660431)   
f   (v, 0.6186830997467041)   (o, 0.5711736083030701)   
v   (o, 0.6923835873603821)   (f, 0.6186829805374146)   
z  (f, 0.49618273973464966)   (q, 0.3221225142478943)   
q  (o, 0.41689175367355347)   (z, 0.3221224844455719)   
x   (c, 0.5699155330657959)   (v, 0.5186272263526917)   

                          2                         3  \
a  (n, 0.42743346095085144)  (b, 0.39250025153160095)   
   (m, 0.12399032711982727)  (s, 0.12370451539754868)   
n   (b, 0.3664851188659668)  (m, 0.34063592553138733)   
i    (v, 0.297261118888855)   (f, 0.2827352285385132)   
e  (p, 0.20635925233364105)  (d, 0.18604975938796997)   
r   (s, 0.3119433522224426)  (v, 0.30897295475006104)   
t   (m, 0.4247564375400543)   (b, 0.3275858163833618)   
k   (b, 0.4105524718761444)   (j, 0.3974840044975281)   
u   (g, 0.3872831165790558)  (m, 0.29255327582359314)   
s  (t, 0.44287970662117004)   (k, 0.3899189233779907)   
m   (d, 0.3959639370441437)   (b, 0.3768627345561981)   
d   (l, 0.3252643644809723)   (t, 0.3162349462509155)   
g   (a, 0.5576417446136475)  (m, 0.48909297585487366)   
p  (k, 0.34793099761009216)  (y, 0.26168784499168396)   
l   (r, 0.3455035388469696)   (d, 0.3252643942832947)   
b   (j, 0.4434639513492584)   (y, 0.4243253469467163)   
o   (f, 0.5711735486984253)   (x, 0.4725012481212616)   
h  (y, 0.34668195247650146)   (g, 0.3420393764972687)   
y  (b, 0.42432528734207153)   (m, 0.3749331533908844)   
j   (k, 0.3974839746952057)   (y, 0.3144787549972534)   
c   (v, 0.5312266945838928)   (f, 0.5200924277305603)   
w  (q, 0.24321354925632477)  (c, 0.11794664710760117)   
f   (c, 0.5200925469398499)  (z, 0.49618276953697205)   
v   (c, 0.5312265753746033)   (x, 0.5186272263526917)   
z   (x, 0.2704002559185028)  (c, 0.24630269408226013)   
q  (f, 0.31953153014183044)   (v, 0.3125038743019104)   
x   (f, 0.4804574251174927)    (o, 0.472501277923584)   

                          4                         5  \
a   (m, 0.3376457989215851)   (y, 0.3203909695148468)   
   (v, 0.11445712298154831)  (p, 0.09365905821323395)   
n  (h, 0.27578747272491455)   (y, 0.2710050344467163)   
i   (s, 0.2552667260169983)   (e, 0.2363346964120865)   
e  (u, 0.18572577834129333)  (g, 0.18534377217292786)   
r  (c, 0.24745267629623413)   (f, 0.2308942675590515)   
t   (d, 0.3162349462509155)  (k, 0.23421476781368256)   
k   (s, 0.3899189531803131)  (p, 0.34793102741241455)   
u  (b, 0.27218297123908997)  (h, 0.24367780983448029)   
s    (m, 0.349176824092865)  (r, 0.31194332242012024)   
m   (y, 0.3749332129955292)   (s, 0.3491768538951874)   
d   (k, 0.2884010672569275)  (b, 0.24462243914604187)   
g   (b, 0.4829775094985962)  (p, 0.42159056663513184)   
p   (m, 0.2509743869304657)  (v, 0

## FastText Corpus Twitter+Berita

In [4]:
df_ntwt = pd.read_csv(r"Twitter_Berita.csv", usecols=['Clean Text'])
df_ntwt.rename(columns = {'Clean Text':'clean_text'}, inplace = True)
df_ntwt

clean_text
0       jakarta badan awas milu dki jakarta tunggu lap...
1       jakarta wakil ketua komisi ix dpr saleh partao...
2       jakarta pasang calon nomor urut anies baswedan...
3       jakarta rumah partai golkar guncang ujung febr...
4       jakarta calon wakil gubernur sandiaga uno masy...
...                                                   ...
159758  sinyal minus tolong baik problem location cama...
159759            punya telkomsel ganggu aduh desak pakai
159760               allah tambah kerja esuk neng grapari
159761  admin sinyal telkomsel rumah daerah rawabunga ...
159762  tante kirim pakai nomor telkomsel langsung gra...

[159763 rows x 1 columns]

In [5]:
df_ntwt['clean_text'] = df_ntwt['clean_text'].apply(str)
df_ntwt['clean_text'] = df_ntwt['clean_text'].astype(np.uint8,errors='ignore')

In [10]:
import nltk
def tokenizing(data):
    return nltk.tokenize.word_tokenize(data)

df_ntwt['clean_text'] = df_ntwt['clean_text'].apply(tokenizing)
df_ntwt

clean_text
0       [jakarta, badan, awas, milu, dki, jakarta, tun...
1       [jakarta, wakil, ketua, komisi, ix, dpr, saleh...
2       [jakarta, pasang, calon, nomor, urut, anies, b...
3       [jakarta, rumah, partai, golkar, guncang, ujun...
4       [jakarta, calon, wakil, gubernur, sandiaga, un...
...                                                   ...
159758  [sinyal, minus, tolong, baik, problem, locatio...
159759     [punya, telkomsel, ganggu, aduh, desak, pakai]
159760        [allah, tambah, kerja, esuk, neng, grapari]
159761  [admin, sinyal, telkomsel, rumah, daerah, rawa...
159762  [tante, kirim, pakai, nomor, telkomsel, langsu...

[159763 rows x 1 columns]

In [11]:
model_ntwt= FastText(sentences = df_ntwt['clean_text'], window = 5, min_count = 3, workers = 4, sg = 0, hs = 0)

In [12]:
os.makedirs("model_ntwt/fasttext/", exist_ok=True)

In [13]:
model_ntwt.save("model_ntwt/fasttext/Twitter_Berita.fasttext")

In [14]:
model_ntwt = FastText.load("model_ntwt/fasttext/Twitter_Berita.fasttext")

In [15]:
ft_ntwt = model_ntwt.wv

In [16]:
ft_ntwt.vectors

array([[ 2.092244  , -0.25190786,  0.2636887 , ..., -0.5609745 ,
         0.77869946, -0.8222434 ],
       [ 0.587322  ,  0.14010432,  2.3640246 , ...,  0.7248826 ,
         0.41952834, -0.16520321],
       [ 1.415151  , -0.5565851 ,  1.2971247 , ..., -0.9862154 ,
        -1.4731423 ,  0.20357457],
       ...,
       [ 0.8263674 , -1.4614772 , -1.9531626 , ...,  0.4013646 ,
        -2.6563537 , -0.3839487 ],
       [-0.25031346,  0.8881827 , -1.5024167 , ..., -1.0973836 ,
         0.41321152,  2.3490376 ],
       [ 0.45583063,  0.44642103,  0.80182743, ...,  1.0687164 ,
        -0.37267807, -0.0194013 ]], dtype=float32)

In [19]:
# coba 
ft_ntwt["sinyal"]

array([ 0.6394048 , -1.369532  , -1.6575286 , -0.47908172, -3.5609512 ,
       -0.12657064,  0.41824493, -0.73568135, -1.0669816 ,  3.5585103 ,
       -0.96128595, -1.3824836 ,  1.735925  , -0.08020652, -0.07789792,
       -0.29125875, -0.47597635, -1.3161237 ,  4.867932  ,  0.1664621 ,
        0.16734684,  1.0056736 ,  1.6144673 , -0.9193991 , -0.72538036,
       -0.4649625 , -0.73020625, -2.0788968 ,  1.1935692 ,  1.2803372 ,
        0.3357062 ,  1.5573152 , -1.053575  , -0.4103037 , -0.526831  ,
       -0.09087374, -1.0578994 ,  0.92822766,  1.6034423 ,  1.5485487 ,
        2.9862137 ,  3.639224  , -1.5408016 , -0.26664767, -2.6576881 ,
        2.5356646 , -2.392368  , -1.111962  ,  1.0661613 , -0.61225843,
       -1.0539875 , -0.21038844,  2.9803112 ,  3.0573473 , -0.9278677 ,
        0.49636832,  1.4581606 ,  1.6673676 ,  1.0008724 , -1.5217627 ,
       -1.4370489 , -1.8604511 ,  1.1608045 ,  1.9946703 ,  0.5853336 ,
        0.05616513,  1.7988462 , -1.0546598 ,  1.8466953 , -1.47

In [24]:
# Train Similarity Model FastText
ft_ntwt.most_similar('upgrade')

[('diupgrade', 0.9359852075576782),
 ('upgradeable', 0.8564543128013611),
 ('mengupgrade', 0.8067767024040222),
 ('grade', 0.7846726775169373),
 ('peergrade', 0.7718490958213806),
 ('downgrade', 0.7615814208984375),
 ('belgrade', 0.7011500597000122),
 ('retrograde', 0.6948543190956116),
 ('update', 0.6821423768997192),
 ('diupdate', 0.677430272102356)]

In [25]:
def word_similarity(text):
    x = []
    for i in text:
        x.append(i[0])
    return x

def create_corpus10(text):
    word = ft_ntwt.most_similar(text, topn=10)
    return word

words10 = ft_ntwt.key_to_index

corpus10 = list(map(create_corpus10, words10))
cfbt10 = pd.DataFrame(corpus10, index=words10)
cfbt10['All'] = corpus10
cfbt10['similarity'] = cfbt10['All'].apply(word_similarity)

cfbt10.to_excel('corpus_twitter_berita.xlsx')

In [26]:
cfbt10

0  \
jakarta         (jakartanya, 0.9309255480766296)   
indonesia      (indonenesia, 0.9577275514602661)   
nbsp               (prakash, 0.5695722103118896)   
rp                    (rprp, 0.9894996881484985)   
perintah         (pmerintah, 0.9208042621612549)   
...                                          ...   
bechtold          (beaumont, 0.7443647980690002)   
relationships     (relation, 0.9359395503997803)   
pekuk                (lekuk, 0.7416641116142273)   
loui                   (lou, 0.7526066899299622)   
rissa                 (risa, 0.7534354329109192)   

                                                 1  \
jakarta             (jakartan, 0.9251999258995056)   
indonesia      (iataindonesia, 0.9291603565216064)   
nbsp                   (rdquo, 0.5336586236953735)   
rp                       (hrp, 0.9657172560691833)   
perintah           (emerintah, 0.9081432223320007)   
...                                            ...   
bechtold                (told, 0.7397733330726624)   
relationships      (relations, 0.9104543328285217)   
pekuk                  (bekuk, 0.7144950032234192)   
loui                  (louise, 0.7331133484840393)   
rissa               (clarissa, 0.7384436726570129)   

                                              2  \
jakarta         (dijakarta, 0.9230458736419678)   
indonesia      (ukindonesia, 0.920493483543396)   
nbsp                (mdash, 0.5205275416374207)   
rp                    (nrp, 0.9610791206359863)   
perintah       (peemrintah, 0.8954433798789978)   
...                                         ...   
bechtold             (mold, 0.7220179438591003)   
relationships  (desolation, 0.8464073538780212)   
pekuk               (kikuk, 0.7079060077667236)   
loui                (louis, 0.7276871800422668)   
rissa               (eissa, 0.6937931180000305)   

                                               3  \
jakarta           (ijakarta, 0.9163376092910767)   
indonesia        (lndonesia, 0.9161185026168823)   
nbsp                 (ndash, 0.5164719820022583)   
rp                      (jrp, 0.944168210029602)   
perintah         (pemrintah, 0.8951194286346436)   
...                                          ...   
bechtold            (cralle, 0.7174791693687439)   
relationships  (compilation, 0.8429555892944336)   
pekuk                     (kuk, 0.7078897356987)   
loui            (louisville, 0.7275723218917847)   
rissa                  (riss, 0.692179262638092)   

                                               4  \
jakarta        (jihdjakarta, 0.9103918671607971)   
indonesia         (ndonesia, 0.9128187298774719)   
nbsp             (depannnya, 0.5047065019607544)   
rp                      (rpg, 0.938391387462616)   
perintah          (merintah, 0.8889585137367249)   
...                                          ...   
bechtold        (goldenberg, 0.7137342095375061)   
relationships   (relaxation, 0.8391841650009155)   
pekuk                (pikuk, 0.6971339583396912)   
loui                 (louie, 0.7091782689094543)   
rissa                  (ris, 0.6728571057319641)   

                                                5  \
jakarta         (jakartaahok, 0.9048116207122803)   
indonesia        (indonesaia, 0.9095563292503357)   
nbsp           (problematika, 0.4924423396587372)   
rp                      (rpw, 0.9178465008735657)   
perintah       (nonpemerintah, 0.883480429649353)   
...                                           ...   
bechtold           (beaufort, 0.7096481919288635)   
relationships   (calculation, 0.8371820449829102)   
pekuk                (kirkuk, 0.6819097995758057)   
loui                     (ith, 0.693231999874115)   
rissa                  (riska, 0.670330822467804)   

                                                   6  \
jakarta            (jakartakota, 0.8980677723884583)   
indonesia       (indonesiaelisa, 0.9068799614906311)   
nbsp           (mengendepankan, 0.48452243208885193)   
rp                        (rptc, 0.89422786235809