In [1]:
import pandas as pd
import numpy as np
import ast
import re
import sklearn
import six
from abc import ABCMeta
from sklearn.base import BaseEstimator, ClassifierMixin
from sklearn.utils.extmath import safe_sparse_dot
from scipy import sparse
import warnings
warnings.filterwarnings('ignore')
import nltk
import six
import re
import gensim
from tqdm import tqdm


from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import LinearSVC
from abc import ABCMeta
from sklearn.pipeline import Pipeline
from sklearn.utils import check_X_y, check_array
from scipy import sparse
from nltk.stem import PorterStemmer,WordNetLemmatizer
from scipy.sparse import issparse
from sklearn.base import BaseEstimator, ClassifierMixin
from sklearn.utils.extmath import safe_sparse_dot
from sklearn.preprocessing import normalize, binarize, LabelBinarizer
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer,TfidfTransformer
from sklearn.utils import resample
from sklearn.metrics import accuracy_score,f1_score
from gensim.models import FastText

In [2]:
tsel = pd.read_csv(r'Prepro_Sinyal.csv', usecols=['Username','Text','Sinyal','text_result'])
tsel

Username                                               Text  \
0      satriafakhri_id  @yamasaiyaa untuk masalah hp lapor aja ke yg b...   
1          Piyuuuuu21_  @bertanyarl Gatau, akhir akhir ini Telkomsel l...   
2          hypersex_pr            Ada kendala kah dengan sinyal telkomsel   
3          snwyscrtimh  @squidwardpemala @Cutimut3 @reihanahsan @sonde...   
4           aninadhany  @Telkomsel min, dari kmrn aplikasi my telkomse...   
...                ...                                                ...   
16986          Syaeeef  Sinyal mines, #sinyal #telkomsel #byu.id tolon...   
16987           abdr40  @Telkomsel ini My Telkomsel gangguan sampe kap...   
16988     thepinediary  yaallah nambah2i gawean waeee esuk2 kudu neng ...   
16989       yudaamaraa  @Telkomsel min sinyal telkomsel di rumah saya ...   
16990        ytojerxhi  @convomf tante nya sender pke nomor apa? kl Te...   

       Sinyal                                        text_result  
0         0.0  ['handphone', 'lapor', 'wajib', 'bantu', 'laca...  
1        -1.0  ['tidak tahu', 'telkomsel', 'lambat', 'kuota',...  
2        -1.0                 ['kendala', 'sinyal', 'telkomsel']  
3         0.0  ['tidak bisa', 'nomor', 'mati', 'dihidupakan',...  
4         0.0  ['admin', 'kemarin', 'aplikasi', 'punya', 'tel...  
...       ...                                                ...  
16986    -1.0  ['sinyal', 'minus', 'tolong', 'baik', 'problem...  
16987    -1.0  ['punya', 'telkomsel', 'ganggu', 'aduh', 'desa...  
16988     0.0  ['allah', 'tambah', 'kerja', 'esuk', 'neng', '...  
16989    -1.0  ['admin', 'sinyal', 'telkomsel', 'rumah', 'dae...  
16990     0.0  ['tante', 'kirim', 'pakai', 'nomor', 'telkomse...  

[16991 rows x 4 columns]

In [3]:
tsel['text_result'] = tsel['text_result'].apply(str)

In [4]:
import ast

def join_text_list(text):
    texts = ast.literal_eval(text)
    return ' '.join([text for text in texts])

tsel['text_result'] = tsel['text_result'].apply(join_text_list)
tsel

Username                                               Text  \
0      satriafakhri_id  @yamasaiyaa untuk masalah hp lapor aja ke yg b...   
1          Piyuuuuu21_  @bertanyarl Gatau, akhir akhir ini Telkomsel l...   
2          hypersex_pr            Ada kendala kah dengan sinyal telkomsel   
3          snwyscrtimh  @squidwardpemala @Cutimut3 @reihanahsan @sonde...   
4           aninadhany  @Telkomsel min, dari kmrn aplikasi my telkomse...   
...                ...                                                ...   
16986          Syaeeef  Sinyal mines, #sinyal #telkomsel #byu.id tolon...   
16987           abdr40  @Telkomsel ini My Telkomsel gangguan sampe kap...   
16988     thepinediary  yaallah nambah2i gawean waeee esuk2 kudu neng ...   
16989       yudaamaraa  @Telkomsel min sinyal telkomsel di rumah saya ...   
16990        ytojerxhi  @convomf tante nya sender pke nomor apa? kl Te...   

       Sinyal                                        text_result  
0         0.0  handphone lapor wajib bantu lacak imei perihal...  
1        -1.0  tidak tahu telkomsel lambat kuota promo murah ...  
2        -1.0                           kendala sinyal telkomsel  
3         0.0  tidak bisa nomor mati dihidupakan grapari nomo...  
4         0.0  admin kemarin aplikasi punya telkomsel ganggu ...  
...       ...                                                ...  
16986    -1.0  sinyal minus tolong baik problem location cama...  
16987    -1.0            punya telkomsel ganggu aduh desak pakai  
16988     0.0               allah tambah kerja esuk neng grapari  
16989    -1.0  admin sinyal telkomsel rumah daerah rawabunga ...  
16990     0.0  tante kirim pakai nomor telkomsel langsung gra...  

[16991 rows x 4 columns]

## Ektraksi Fitur TF-IDF 

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(tsel['text_result'], tsel['Sinyal'], test_size=0.2, random_state=25)

In [9]:
vectors= TfidfVectorizer(ngram_range=(1,2), max_features = 1000)
vectors

TfidfVectorizer(max_features=1000, ngram_range=(1, 2))

In [25]:
tfidfx_train = vectors.fit_transform(x_train.astype(str))
tfidfx_test = vectors.transform(x_test.astype(str))

In [26]:
tsel['Sinyal'].value_counts()

-1.0    9643
 0.0    6877
 1.0     471
Name: Sinyal, dtype: int64

## Ekspansi Fitur

In [27]:
# Load Model trained
model_exp = FastText.load('model_ntwt/fasttext/Twitter_Berita.fasttext').wv

In [95]:
def feature_expansion(df,feature):
    for col in tqdm(df.columns): #loop per kolom
        try: 
            sim_word = model_exp.similar_by_word(col, topn = 20) #Mencari similarity berdasarkan nilai n
        except:
            sim_word = []
        if sim_word != []: #jika similarity tidak kosong
            for term in [sim_word[i][0] for i in range(len(sim_word))]: #loop per-word yang ada di Similarity
                if term in feature:
                    #untuk semua kolom yang mempunyai nilai 0 di kolom, tetapi mempunyai nilai yang bukan 0 pada kolom term
                    #nilainya diganti dengan nilai kolom term yang mempunyai nilai bukan 0
                    df[col][(df[col]==0) & (df[term]!=0)] = df[term][(df[col]==0) & (df[term]!=0)]
    return df

In [96]:
feature_ef = vectors.get_feature_names()

In [97]:
# Membuat dataframe data test & train
tsel_x_train = pd.DataFrame(tfidfx_train.todense(), columns = feature_ef)
tsel_x_test = pd.DataFrame(tfidfx_test.todense(), columns = feature_ef)

In [98]:
dfexp_x_train= feature_expansion(tsel_x_train, feature_ef)

100%|██████████| 1000/1000 [00:10<00:00, 98.18it/s]


In [99]:
dfexp_x_test = feature_expansion(tsel_x_test, feature_ef)

100%|██████████| 1000/1000 [00:08<00:00, 112.24it/s]


## Klasifikasi

In [100]:
class NBSVM(six.with_metaclass(ABCMeta, BaseEstimator, ClassifierMixin)):
    def __init__(self, alpha=1.0, C=1.0, max_iter=10000):
        self.alpha = alpha
        self.max_iter = max_iter
        self.C = C
        self.svm_ = [] # fuggly

    def fit(self, X, y):
        X, y = check_X_y(X, y, 'csr')
        _, n_features = X.shape

        labelbin = LabelBinarizer()
        Y = labelbin.fit_transform(y)
        self.classes_ = labelbin.classes_
        if Y.shape[1] == 1:
            Y = np.concatenate((1 - Y, Y), axis=1)

        # LabelBinarizer().fit_transform() returns arrays with dtype=np.int64.
        # so we don't have to cast X to floating point
        Y = Y.astype(np.float64)

        # Count raw events from data
        n_effective_classes = Y.shape[1]
        self.class_count_ = np.zeros(n_effective_classes, dtype=np.float64)
        self.ratios_ = np.full((n_effective_classes, n_features), self.alpha,
                                 dtype=np.float64)
        self._compute_ratios(X, Y)

        # flugglyness
        for i in range(n_effective_classes):
            X_i = X.multiply(self.ratios_[i])
            svm = LinearSVC(C=self.C, max_iter=self.max_iter)
            Y_i = Y[:,i]
            svm.fit(X_i, Y_i)
            self.svm_.append(svm) 

        return self

    def predict(self, X):
        n_effective_classes = self.class_count_.shape[0]
        n_examples = X.shape[0]

        D = np.zeros((n_effective_classes, n_examples))

        for i in range(n_effective_classes):
            X_i = X.multiply(self.ratios_[i])
            D[i] = self.svm_[i].decision_function(X_i)
        
        return self.classes_[np.argmax(D, axis=0)]
        
    def _compute_ratios(self, X, Y):
        """Count feature occurrences and compute ratios."""
        if np.any((X.data if issparse(X) else X) < 0):
            raise ValueError("Input X must be non-negative")

        self.ratios_ += safe_sparse_dot(Y.T, X)  # ratio + feature_occurrance_c
        normalize(self.ratios_, norm='l1', axis=1, copy=False)
        row_calc = lambda r: np.log(np.divide(r, (1 - r)))
        self.ratios_ = np.apply_along_axis(row_calc, axis=1, arr=self.ratios_)
        check_array(self.ratios_)
        self.ratios_ = sparse.csr_matrix(self.ratios_)

In [101]:
x_train_csr = sparse.csr_matrix(dfexp_x_train)
x_test_csr = sparse.csr_matrix(dfexp_x_test)
model = NBSVM()

model.fit(x_train_csr,y_train)
y_pred_exp = model.predict(x_test_csr)
y_true = y_test

### Top 1

In [93]:
#example training
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
#[None, 'micro', 'macro', 'weighted'].
print(confusion_matrix(y_true,y_pred_exp))
print(classification_report(y_true,y_pred_exp))
print("Precision: ",precision_score(y_true, y_pred_exp, average="macro"))
print("Recall: ",recall_score(y_true, y_pred_exp, average="macro"))
print("F1: ",f1_score(y_true, y_pred_exp,  average="macro"))
print("Accuracy: ",accuracy_score(y_true, y_pred_exp))

[[1844   64   21]
 [  94 1272    9]
 [  62    9   24]]
              precision    recall  f1-score   support

        -1.0       0.92      0.96      0.94      1929
         0.0       0.95      0.93      0.94      1375
         1.0       0.44      0.25      0.32        95

    accuracy                           0.92      3399
   macro avg       0.77      0.71      0.73      3399
weighted avg       0.92      0.92      0.92      3399

Precision:  0.7707231171692138
Recall:  0.7112194020089575
F1:  0.7320343352032462
Accuracy:  0.9238011179758753


In [94]:
#### ROC-AUC

from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder(handle_unknown='ignore')
y_pred_roc = enc.fit_transform(np.array(y_pred_exp).reshape(-1,1))
Y_pred = y_pred_roc.toarray()

y_true_r = enc.fit_transform(np.array(y_true).reshape(-1,1))
y_true_roc = y_true_r.toarray()

from sklearn.metrics import roc_auc_score
roc_auc_score(y_true_roc,Y_pred, multi_class='ovr')

0.830398110037282

### Top 5

In [71]:
#example training
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
#[None, 'micro', 'macro', 'weighted'].
print(confusion_matrix(y_true,y_pred_exp))
print(classification_report(y_true,y_pred_exp))
print("Precision: ",precision_score(y_true, y_pred_exp, average="macro"))
print("Recall: ",recall_score(y_true, y_pred_exp, average="macro"))
print("F1: ",f1_score(y_true, y_pred_exp,  average="macro"))
print("Accuracy: ",accuracy_score(y_true, y_pred_exp))

[[1836   67   26]
 [  93 1273    9]
 [  61    9   25]]
              precision    recall  f1-score   support

        -1.0       0.92      0.95      0.94      1929
         0.0       0.94      0.93      0.93      1375
         1.0       0.42      0.26      0.32        95

    accuracy                           0.92      3399
   macro avg       0.76      0.71      0.73      3399
weighted avg       0.92      0.92      0.92      3399

Precision:  0.7609805679414285
Recall:  0.7135881893337898
F1:  0.7314030940609522
Accuracy:  0.9220358929096794


In [72]:
#### ROC-AUC

from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder(handle_unknown='ignore')
y_pred_roc = enc.fit_transform(np.array(y_pred_exp).reshape(-1,1))
Y_pred = y_pred_roc.toarray()

y_true_r = enc.fit_transform(np.array(y_true).reshape(-1,1))
y_true_roc = y_true_r.toarray()

from sklearn.metrics import roc_auc_score
roc_auc_score(y_true_roc,Y_pred, multi_class='ovr')

0.8313100059643096

### Top 10

In [80]:
#example training
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
#[None, 'micro', 'macro', 'weighted'].
print(confusion_matrix(y_true,y_pred_exp))
print(classification_report(y_true,y_pred_exp))
print("Precision: ",precision_score(y_true, y_pred_exp, average="macro"))
print("Recall: ",recall_score(y_true, y_pred_exp, average="macro"))
print("F1: ",f1_score(y_true, y_pred_exp,  average="macro"))
print("Accuracy: ",accuracy_score(y_true, y_pred_exp))

[[1835   66   28]
 [ 103 1261   11]
 [  62    9   24]]
              precision    recall  f1-score   support

        -1.0       0.92      0.95      0.93      1929
         0.0       0.94      0.92      0.93      1375
         1.0       0.38      0.25      0.30        95

    accuracy                           0.92      3399
   macro avg       0.75      0.71      0.72      3399
weighted avg       0.91      0.92      0.91      3399

Precision:  0.7474382188004943
Recall:  0.7069975253889472
F1:  0.7227204716475685
Accuracy:  0.9179170344218888


In [81]:
#### ROC-AUC

from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder(handle_unknown='ignore')
y_pred_roc = enc.fit_transform(np.array(y_pred_exp).reshape(-1,1))
Y_pred = y_pred_roc.toarray()

y_true_r = enc.fit_transform(np.array(y_true).reshape(-1,1))
y_true_roc = y_true_r.toarray()

from sklearn.metrics import roc_auc_score
roc_auc_score(y_true_roc,Y_pred, multi_class='ovr')

0.8266480780245448

### Top 20

In [102]:
#example training
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
#[None, 'micro', 'macro', 'weighted'].
print(confusion_matrix(y_true,y_pred_exp))
print(classification_report(y_true,y_pred_exp))
print("Precision: ",precision_score(y_true, y_pred_exp, average="macro"))
print("Recall: ",recall_score(y_true, y_pred_exp, average="macro"))
print("F1: ",f1_score(y_true, y_pred_exp,  average="macro"))
print("Accuracy: ",accuracy_score(y_true, y_pred_exp))

[[1827   72   30]
 [  89 1271   15]
 [  61   10   24]]
              precision    recall  f1-score   support

        -1.0       0.92      0.95      0.94      1929
         0.0       0.94      0.92      0.93      1375
         1.0       0.35      0.25      0.29        95

    accuracy                           0.92      3399
   macro avg       0.74      0.71      0.72      3399
weighted avg       0.91      0.92      0.92      3399

Precision:  0.7371158307359403
Recall:  0.708039358965773
F1:  0.7199949932050639
Accuracy:  0.9185054427772874


In [103]:
#### ROC-AUC

from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder(handle_unknown='ignore')
y_pred_roc = enc.fit_transform(np.array(y_pred_exp).reshape(-1,1))
Y_pred = y_pred_roc.toarray()

y_true_r = enc.fit_transform(np.array(y_true).reshape(-1,1))
y_true_roc = y_true_r.toarray()

from sklearn.metrics import roc_auc_score
roc_auc_score(y_true_roc,Y_pred, multi_class='ovr')

0.827990595309524