In [ ]:
import pandas as pd
import numpy as np
import ast
import re
import sklearn
import six
from abc import ABCMeta
from sklearn.base import BaseEstimator, ClassifierMixin
from sklearn.utils.extmath import safe_sparse_dot
from scipy import sparse
import warnings
warnings.filterwarnings('ignore')
import nltk
import six
import re
import gensim

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import LinearSVC
from abc import ABCMeta
from sklearn.pipeline import Pipeline
from sklearn.utils import check_X_y, check_array
from scipy import sparse
from nltk.stem import PorterStemmer,WordNetLemmatizer
from scipy.sparse import issparse
from sklearn.base import BaseEstimator, ClassifierMixin
from sklearn.utils.extmath import safe_sparse_dot
from sklearn.preprocessing import normalize, binarize, LabelBinarizer
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer,TfidfTransformer
from sklearn.utils import resample
from sklearn.metrics import accuracy_score,f1_score

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
tsel = pd.read_csv(r'/content/drive/MyDrive/TA/Prepro_Sinyal.csv', usecols=['Username','Text','Sinyal','text_result'])
tsel

Username                                               Text  \
0      satriafakhri_id  @yamasaiyaa untuk masalah hp lapor aja ke yg b...   
1          Piyuuuuu21_  @bertanyarl Gatau, akhir akhir ini Telkomsel l...   
2          hypersex_pr            Ada kendala kah dengan sinyal telkomsel   
3          snwyscrtimh  @squidwardpemala @Cutimut3 @reihanahsan @sonde...   
4           aninadhany  @Telkomsel min, dari kmrn aplikasi my telkomse...   
...                ...                                                ...   
16986          Syaeeef  Sinyal mines, #sinyal #telkomsel #byu.id tolon...   
16987           abdr40  @Telkomsel ini My Telkomsel gangguan sampe kap...   
16988     thepinediary  yaallah nambah2i gawean waeee esuk2 kudu neng ...   
16989       yudaamaraa  @Telkomsel min sinyal telkomsel di rumah saya ...   
16990        ytojerxhi  @convomf tante nya sender pke nomor apa? kl Te...   

       Sinyal                                        text_result  
0         0.0  ['handphone', 'lapor', 'wajib', 'bantu', 'laca...  
1        -1.0  ['tidak tahu', 'telkomsel', 'lambat', 'kuota',...  
2        -1.0                 ['kendala', 'sinyal', 'telkomsel']  
3         0.0  ['tidak bisa', 'nomor', 'mati', 'dihidupakan',...  
4         0.0  ['admin', 'kemarin', 'aplikasi', 'punya', 'tel...  
...       ...                                                ...  
16986    -1.0  ['sinyal', 'minus', 'tolong', 'baik', 'problem...  
16987    -1.0  ['punya', 'telkomsel', 'ganggu', 'aduh', 'desa...  
16988     0.0  ['allah', 'tambah', 'kerja', 'esuk', 'neng', '...  
16989    -1.0  ['admin', 'sinyal', 'telkomsel', 'rumah', 'dae...  
16990     0.0  ['tante', 'kirim', 'pakai', 'nomor', 'telkomse...  

[16991 rows x 4 columns]

In [ ]:
tsel['text_result'] = tsel['text_result'].apply(str)

In [ ]:
import ast

def join_text_list(text):
    texts = ast.literal_eval(text)
    return ' '.join([text for text in texts])

tsel['text_result'] = tsel['text_result'].apply(join_text_list)
tsel

Username                                               Text  \
0      satriafakhri_id  @yamasaiyaa untuk masalah hp lapor aja ke yg b...   
1          Piyuuuuu21_  @bertanyarl Gatau, akhir akhir ini Telkomsel l...   
2          hypersex_pr            Ada kendala kah dengan sinyal telkomsel   
3          snwyscrtimh  @squidwardpemala @Cutimut3 @reihanahsan @sonde...   
4           aninadhany  @Telkomsel min, dari kmrn aplikasi my telkomse...   
...                ...                                                ...   
16986          Syaeeef  Sinyal mines, #sinyal #telkomsel #byu.id tolon...   
16987           abdr40  @Telkomsel ini My Telkomsel gangguan sampe kap...   
16988     thepinediary  yaallah nambah2i gawean waeee esuk2 kudu neng ...   
16989       yudaamaraa  @Telkomsel min sinyal telkomsel di rumah saya ...   
16990        ytojerxhi  @convomf tante nya sender pke nomor apa? kl Te...   

       Sinyal                                        text_result  
0         0.0  handphone lapor wajib bantu lacak imei perihal...  
1        -1.0  tidak tahu telkomsel lambat kuota promo murah ...  
2        -1.0                           kendala sinyal telkomsel  
3         0.0  tidak bisa nomor mati dihidupakan grapari nomo...  
4         0.0  admin kemarin aplikasi punya telkomsel ganggu ...  
...       ...                                                ...  
16986    -1.0  sinyal minus tolong baik problem location cama...  
16987    -1.0            punya telkomsel ganggu aduh desak pakai  
16988     0.0               allah tambah kerja esuk neng grapari  
16989    -1.0  admin sinyal telkomsel rumah daerah rawabunga ...  
16990     0.0  tante kirim pakai nomor telkomsel langsung gra...  

[16991 rows x 4 columns]

## Ektraksi Fitur TF-IDF 

In [ ]:
%%time
# Creating the sklearn object
tfidf = sklearn.feature_extraction.text.TfidfVectorizer(ngram_range=(1, 2), max_features=1000)

# Transforming our 'tokens' column into a TF-IDF matrix and then a data frame
tfidf_df = pd.DataFrame(tfidf.fit_transform(tsel['text_result']).toarray(), 
                        columns=tfidf.get_feature_names())

CPU times: user 526 ms, sys: 97.5 ms, total: 624 ms
Wall time: 628 ms


In [ ]:
tfidf_df

ada     admin  admin aplikasi  admin beli  admin grapari  admin jaring  \
0      0.0  0.000000             0.0         0.0            0.0           0.0   
1      0.0  0.000000             0.0         0.0            0.0           0.0   
2      0.0  0.000000             0.0         0.0            0.0           0.0   
3      0.0  0.000000             0.0         0.0            0.0           0.0   
4      0.0  0.179169             0.0         0.0            0.0           0.0   
...    ...       ...             ...         ...            ...           ...   
16986  0.0  0.000000             0.0         0.0            0.0           0.0   
16987  0.0  0.000000             0.0         0.0            0.0           0.0   
16988  0.0  0.000000             0.0         0.0            0.0           0.0   
16989  0.0  0.200917             0.0         0.0            0.0           0.0   
16990  0.0  0.000000             0.0         0.0            0.0           0.0   

       admin nomor  admin sinyal  admin telkomsel  admin tolong  ...  yaa  \
0              0.0      0.000000              0.0           0.0  ...  0.0   
1              0.0      0.000000              0.0           0.0  ...  0.0   
2              0.0      0.000000              0.0           0.0  ...  0.0   
3              0.0      0.000000              0.0           0.0  ...  0.0   
4              0.0      0.000000              0.0           0.0  ...  0.0   
...            ...           ...              ...           ...  ...  ...   
16986          0.0      0.000000              0.0           0.0  ...  0.0   
16987          0.0      0.000000              0.0           0.0  ...  0.0   
16988          0.0      0.000000              0.0           0.0  ...  0.0   
16989          0.0      0.349052              0.0           0.0  ...  0.0   
16990          0.0      0.000000              0.0           0.0  ...  0.0   

       yaaa  yasudah   yo  youtube  yth  yth paket  zaman  zoom  zoom pro  
0       0.0      0.0  0.0      0.0  0.0        0.0    0.0   0.0       0.0  
1       0.0      0.0  0.0      0.0  0.0        0.0    0.0   0.0       0.0  
2       0.0      0.0  0.0      0.0  0.0        0.0    0.0   0.0       0.0  
3       0.0      0.0  0.0      0.0  0.0        0.0    0.0   0.0       0.0  
4       0.0      0.0  0.0      0.0  0.0        0.0    0.0   0.0       0.0  
...     ...      ...  ...      ...  ...        ...    ...   ...       ...  
16986   0.0      0.0  0.0      0.0  0.0        0.0    0.0   0.0       0.0  
16987   0.0      0.0  0.0      0.0  0.0        0.0    0.0   0.0       0.0  
16988   0.0      0.0  0.0      0.0  0.0        0.0    0.0   0.0       0.0  
16989   0.0      0.0  0.0      0.0  0.0        0.0    0.0   0.0       0.0  
16990   0.0      0.0  0.0      0.0  0.0        0.0    0.0   0.0       0.0  

[16991 rows x 1000 columns]

In [ ]:
tfidf_vectors = tfidf.fit_transform(tsel['text_result'])

In [ ]:
vect_score = np.asarray(tfidf_vectors.mean(axis=0)).ravel().tolist()
tsel_weight = pd.DataFrame({'term': tfidf.get_feature_names(), 'weight': vect_score})
tsel_weight.sort_values(by='weight',ascending=False,inplace=True)
tsel_weight.reset_index(inplace=True)
tsel_weight.drop(['index'], axis='columns', inplace=True)
tsel_weight.head()

term    weight
0  telkomsel  0.102464
1     lambat  0.067736
2     sinyal  0.064047
3     jaring  0.057322
4    grapari  0.056099

In [ ]:
tfidf_vec = tfidf_df.copy()

In [ ]:
tsel['Sinyal'].value_counts()

-1.0    9643
 0.0    6877
 1.0     471
Name: Sinyal, dtype: int64

In [ ]:
X = tfidf_vec
y = tsel['Sinyal']


In [ ]:
tsel.iloc[3577]

Username                                                 ggummyn
Text           Aduh.. sinyal Telkomsel please be nice. Jangan...
Sinyal                                                      -1.0
text_result    aduh sinyal telkomsel tolong be ganggu malam m...
Name: 3577, dtype: object

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y, test_size=0.2, random_state=50)

## Klasifikasi NBSVM

In [ ]:
class NBSVM(six.with_metaclass(ABCMeta, BaseEstimator, ClassifierMixin)):
    def __init__(self, alpha=1.0, C=1.0, max_iter=10000):
        self.alpha = alpha
        self.max_iter = max_iter
        self.C = C
        self.svm_ = [] # fuggly

    def fit(self, X, y):
        X, y = check_X_y(X, y, 'csr')
        _, n_features = X.shape

        labelbin = LabelBinarizer()
        Y = labelbin.fit_transform(y)
        self.classes_ = labelbin.classes_
        if Y.shape[1] == 1:
            Y = np.concatenate((1 - Y, Y), axis=1)

        # LabelBinarizer().fit_transform() returns arrays with dtype=np.int64.
        # so we don't have to cast X to floating point
        Y = Y.astype(np.float64)

        # Count raw events from data
        n_effective_classes = Y.shape[1]
        self.class_count_ = np.zeros(n_effective_classes, dtype=np.float64)
        self.ratios_ = np.full((n_effective_classes, n_features), self.alpha,
                                 dtype=np.float64)
        self._compute_ratios(X, Y)

        # flugglyness
        for i in range(n_effective_classes):
            X_i = X.multiply(self.ratios_[i])
            svm = LinearSVC(C=self.C, max_iter=self.max_iter)
            Y_i = Y[:,i]
            svm.fit(X_i, Y_i)
            self.svm_.append(svm) 

        return self

    def predict(self, X):
        n_effective_classes = self.class_count_.shape[0]
        n_examples = X.shape[0]

        D = np.zeros((n_effective_classes, n_examples))

        for i in range(n_effective_classes):
            X_i = X.multiply(self.ratios_[i])
            D[i] = self.svm_[i].decision_function(X_i)
        
        return self.classes_[np.argmax(D, axis=0)]
        
    def _compute_ratios(self, X, Y):
        """Count feature occurrences and compute ratios."""
        if np.any((X.data if issparse(X) else X) < 0):
            raise ValueError("Input X must be non-negative")

        self.ratios_ += safe_sparse_dot(Y.T, X)  # ratio + feature_occurrance_c
        normalize(self.ratios_, norm='l1', axis=1, copy=False)
        row_calc = lambda r: np.log(np.divide(r, (1 - r)))
        self.ratios_ = np.apply_along_axis(row_calc, axis=1, arr=self.ratios_)
        check_array(self.ratios_)
        self.ratios_ = sparse.csr_matrix(self.ratios_)

In [ ]:
x_train_csr = sparse.csr_matrix(x_train)
x_test_csr = sparse.csr_matrix(x_test)
model = NBSVM()

model.fit(x_train_csr,y_train)
y_pred = model.predict(x_test_csr)
y_true = y_test

### random 5

In [ ]:
#example training
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
#[None, 'micro', 'macro', 'weighted'].
print(confusion_matrix(y_true,y_pred))
print(classification_report(y_true,y_pred))
print("Precision: ",precision_score(y_true, y_pred, average="macro"))
print("Recall: ",recall_score(y_true, y_pred, average="macro"))
print("F1: ",f1_score(y_true, y_pred,  average="macro"))
print("Accuracy: ",accuracy_score(y_true, y_pred))

[[1807   74   28]
 [ 100 1281   13]
 [  58    8   30]]
              precision    recall  f1-score   support

        -1.0       0.92      0.95      0.93      1909
         0.0       0.94      0.92      0.93      1394
         1.0       0.42      0.31      0.36        96

    accuracy                           0.92      3399
   macro avg       0.76      0.73      0.74      3399
weighted avg       0.91      0.92      0.92      3399

Precision:  0.7606555593094327
Recall:  0.7260023970875705
F1:  0.740479429949064
Accuracy:  0.9173286260664901


### random 25

In [ ]:
#example training
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
#[None, 'micro', 'macro', 'weighted'].
print(confusion_matrix(y_true,y_pred))
print(classification_report(y_true,y_pred))
print("Precision: ",precision_score(y_true, y_pred, average="macro"))
print("Recall: ",recall_score(y_true, y_pred, average="macro"))
print("F1: ",f1_score(y_true, y_pred,  average="macro"))
print("Accuracy: ",accuracy_score(y_true, y_pred))

[[1836   66   27]
 [  95 1273    7]
 [  58    9   28]]
              precision    recall  f1-score   support

        -1.0       0.92      0.95      0.94      1929
         0.0       0.94      0.93      0.93      1375
         1.0       0.45      0.29      0.36        95

    accuracy                           0.92      3399
   macro avg       0.77      0.72      0.74      3399
weighted avg       0.92      0.92      0.92      3399

Precision:  0.7730172813689613
Recall:  0.7241145051232634
F1:  0.7429663085283607
Accuracy:  0.9229185054427773


### random 50

In [ ]:
#example training
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
#[None, 'micro', 'macro', 'weighted'].
print(confusion_matrix(y_true,y_pred))
print(classification_report(y_true,y_pred))
print("Precision: ",precision_score(y_true, y_pred, average="macro"))
print("Recall: ",recall_score(y_true, y_pred, average="macro"))
print("F1: ",f1_score(y_true, y_pred,  average="macro"))
print("Accuracy: ",accuracy_score(y_true, y_pred))

[[1860   61   27]
 [ 108 1238    8]
 [  56    8   33]]
              precision    recall  f1-score   support

        -1.0       0.92      0.95      0.94      1948
         0.0       0.95      0.91      0.93      1354
         1.0       0.49      0.34      0.40        97

    accuracy                           0.92      3399
   macro avg       0.78      0.74      0.76      3399
weighted avg       0.92      0.92      0.92      3399

Precision:  0.7838245982426345
Recall:  0.7364531882871526
F1:  0.7556777184750222
Accuracy:  0.9211532803765814
