In [1]:
!pip -q install pyspellchecker optuna

In [8]:
import pandas as pd
import numpy as np
import ast
import re
import sklearn
import six
import optuna
from abc import ABCMeta
from sklearn.base import BaseEstimator, ClassifierMixin
from sklearn.utils.extmath import safe_sparse_dot
from scipy import sparse
import warnings
warnings.filterwarnings('ignore')
import nltk
import six
import re
import gensim

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import LinearSVC
from abc import ABCMeta
from sklearn.pipeline import Pipeline
from sklearn.utils import check_X_y, check_array
from scipy import sparse
from nltk.stem import PorterStemmer,WordNetLemmatizer
from scipy.sparse import issparse
from sklearn.base import BaseEstimator, ClassifierMixin
from sklearn.utils.extmath import safe_sparse_dot
from sklearn.preprocessing import normalize, binarize, LabelBinarizer
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer,TfidfTransformer
from sklearn.utils import resample
from sklearn.metrics import accuracy_score,f1_score

In [9]:
tsel = pd.read_csv(r'Prepro_Sinyal.csv', usecols=['Username','Text','Sinyal','text_result'])
tsel

Username                                               Text  \
0      satriafakhri_id  @yamasaiyaa untuk masalah hp lapor aja ke yg b...   
1          Piyuuuuu21_  @bertanyarl Gatau, akhir akhir ini Telkomsel l...   
2          hypersex_pr            Ada kendala kah dengan sinyal telkomsel   
3          snwyscrtimh  @squidwardpemala @Cutimut3 @reihanahsan @sonde...   
4           aninadhany  @Telkomsel min, dari kmrn aplikasi my telkomse...   
...                ...                                                ...   
16986          Syaeeef  Sinyal mines, #sinyal #telkomsel #byu.id tolon...   
16987           abdr40  @Telkomsel ini My Telkomsel gangguan sampe kap...   
16988     thepinediary  yaallah nambah2i gawean waeee esuk2 kudu neng ...   
16989       yudaamaraa  @Telkomsel min sinyal telkomsel di rumah saya ...   
16990        ytojerxhi  @convomf tante nya sender pke nomor apa? kl Te...   

       Sinyal                                        text_result  
0         0.0  ['handphone', 'lapor', 'wajib', 'bantu', 'laca...  
1        -1.0  ['tidak tahu', 'telkomsel', 'lambat', 'kuota',...  
2        -1.0                 ['kendala', 'sinyal', 'telkomsel']  
3         0.0  ['tidak bisa', 'nomor', 'mati', 'dihidupakan',...  
4         0.0  ['admin', 'kemarin', 'aplikasi', 'punya', 'tel...  
...       ...                                                ...  
16986    -1.0  ['sinyal', 'minus', 'tolong', 'baik', 'problem...  
16987    -1.0  ['punya', 'telkomsel', 'ganggu', 'aduh', 'desa...  
16988     0.0  ['allah', 'tambah', 'kerja', 'esuk', 'neng', '...  
16989    -1.0  ['admin', 'sinyal', 'telkomsel', 'rumah', 'dae...  
16990     0.0  ['tante', 'kirim', 'pakai', 'nomor', 'telkomse...  

[16991 rows x 4 columns]

In [10]:
tsel['text_result'] = tsel['text_result'].apply(str)

In [11]:
import ast

def join_text_list(text):
    texts = ast.literal_eval(text)
    return ' '.join([text for text in texts])

tsel['text_result'] = tsel['text_result'].apply(join_text_list)
tsel

Username                                               Text  \
0      satriafakhri_id  @yamasaiyaa untuk masalah hp lapor aja ke yg b...   
1          Piyuuuuu21_  @bertanyarl Gatau, akhir akhir ini Telkomsel l...   
2          hypersex_pr            Ada kendala kah dengan sinyal telkomsel   
3          snwyscrtimh  @squidwardpemala @Cutimut3 @reihanahsan @sonde...   
4           aninadhany  @Telkomsel min, dari kmrn aplikasi my telkomse...   
...                ...                                                ...   
16986          Syaeeef  Sinyal mines, #sinyal #telkomsel #byu.id tolon...   
16987           abdr40  @Telkomsel ini My Telkomsel gangguan sampe kap...   
16988     thepinediary  yaallah nambah2i gawean waeee esuk2 kudu neng ...   
16989       yudaamaraa  @Telkomsel min sinyal telkomsel di rumah saya ...   
16990        ytojerxhi  @convomf tante nya sender pke nomor apa? kl Te...   

       Sinyal                                        text_result  
0         0.0  handphone lapor wajib bantu lacak imei perihal...  
1        -1.0  tidak tahu telkomsel lambat kuota promo murah ...  
2        -1.0                           kendala sinyal telkomsel  
3         0.0  tidak bisa nomor mati dihidupakan grapari nomo...  
4         0.0  admin kemarin aplikasi punya telkomsel ganggu ...  
...       ...                                                ...  
16986    -1.0  sinyal minus tolong baik problem location cama...  
16987    -1.0            punya telkomsel ganggu aduh desak pakai  
16988     0.0               allah tambah kerja esuk neng grapari  
16989    -1.0  admin sinyal telkomsel rumah daerah rawabunga ...  
16990     0.0  tante kirim pakai nomor telkomsel langsung gra...  

[16991 rows x 4 columns]

In [12]:
from sklearn.feature_extraction.text import CountVectorizer
matrix = CountVectorizer(max_features=1000)
vectors = matrix.fit_transform(tsel['text_result']).toarray()

In [13]:
tsel['Sinyal'].value_counts()

-1.0    9643
 0.0    6877
 1.0     471
Name: Sinyal, dtype: int64

In [14]:
X = vectors
y = tsel['Sinyal']

X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y, test_size=0.2, random_state=5)

## Klasifikasi NBSVM

In [16]:
class NBSVM(six.with_metaclass(ABCMeta, BaseEstimator, ClassifierMixin)):
    def __init__(self, alpha=1.0, C=1.0, max_iter=10000):
        self.alpha = alpha
        self.max_iter = max_iter
        self.C = C
        self.svm_ = [] # fuggly

    def fit(self, X, y):
        X, y = check_X_y(X, y, 'csr')
        _, n_features = X.shape

        labelbin = LabelBinarizer()
        Y = labelbin.fit_transform(y)
        self.classes_ = labelbin.classes_
        if Y.shape[1] == 1:
            Y = np.concatenate((1 - Y, Y), axis=1)

        # LabelBinarizer().fit_transform() returns arrays with dtype=np.int64.
        # so we don't have to cast X to floating point
        Y = Y.astype(np.float64)

        # Count raw events from data
        n_effective_classes = Y.shape[1]
        self.class_count_ = np.zeros(n_effective_classes, dtype=np.float64)
        self.ratios_ = np.full((n_effective_classes, n_features), self.alpha,
                                 dtype=np.float64)
        self._compute_ratios(X, Y)

        # flugglyness
        for i in range(n_effective_classes):
            X_i = X.multiply(self.ratios_[i])
            svm = LinearSVC(C=self.C, max_iter=self.max_iter)
            Y_i = Y[:,i]
            svm.fit(X_i, Y_i)
            self.svm_.append(svm) 

        return self

    def predict(self, X):
        n_effective_classes = self.class_count_.shape[0]
        n_examples = X.shape[0]

        D = np.zeros((n_effective_classes, n_examples))

        for i in range(n_effective_classes):
            X_i = X.multiply(self.ratios_[i])
            D[i] = self.svm_[i].decision_function(X_i)
        
        return self.classes_[np.argmax(D, axis=0)]
        
    def _compute_ratios(self, X, Y):
        """Count feature occurrences and compute ratios."""
        if np.any((X.data if issparse(X) else X) < 0):
            raise ValueError("Input X must be non-negative")

        self.ratios_ += safe_sparse_dot(Y.T, X)  # ratio + feature_occurrance_c
        normalize(self.ratios_, norm='l1', axis=1, copy=False)
        row_calc = lambda r: np.log(np.divide(r, (1 - r)))
        self.ratios_ = np.apply_along_axis(row_calc, axis=1, arr=self.ratios_)
        check_array(self.ratios_)
        self.ratios_ = sparse.csr_matrix(self.ratios_)

In [17]:
x_train_csr = sparse.csr_matrix(x_train)
x_test_csr = sparse.csr_matrix(x_test)
# model = NBSVM()

# model.fit(x_train_csr,y_train)
# y_pred = model.predict(x_test_csr)
# y_true = y_test

In [18]:
def objective(trial):
    C = trial.suggest_float(name="C", low=1e2, high=1e4, log=True)
    max_iter = trial.suggest_discrete_uniform(name="max_iter", low=50, high=500, q=50)
    nbsvm = NBSVM(C=C, max_iter=max_iter)
    
    nbsvm.fit(x_train_csr, y_train)
    
    y_preds = nbsvm.predict(x_test_csr)
    y_preds[y_preds>=0.5] = 1
    y_preds[y_preds<0.5] = 0
    
    acc = accuracy_score(y_test, y_preds)
    return acc

In [92]:
study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100,show_progress_bar=True)

[I 2022-07-07 22:34:04,254] A new study created in memory with name: no-name-2eb733c0-c318-4df4-a025-8a9541af3302


  0%|          | 0/100 [00:00<?, ?it/s]

[I 2022-07-07 22:34:04,514] Trial 0 finished with value: 0.4148278905560459 and parameters: {'C': 103.8786405632356, 'max_iter': 150.0}. Best is trial 0 with value: 0.4148278905560459.
[I 2022-07-07 22:34:04,826] Trial 1 finished with value: 0.4145336863783466 and parameters: {'C': 4457.1884769851995, 'max_iter': 200.0}. Best is trial 0 with value: 0.4148278905560459.
[I 2022-07-07 22:34:05,294] Trial 2 finished with value: 0.4127684613121506 and parameters: {'C': 1496.4258161821385, 'max_iter': 350.0}. Best is trial 0 with value: 0.4148278905560459.
[I 2022-07-07 22:34:05,466] Trial 3 finished with value: 0.41512209473374523 and parameters: {'C': 1175.1006750980189, 'max_iter': 100.0}. Best is trial 3 with value: 0.41512209473374523.
[I 2022-07-07 22:34:06,142] Trial 4 finished with value: 0.412180052956752 and parameters: {'C': 2939.6089808499405, 'max_iter': 500.0}. Best is trial 3 with value: 0.41512209473374523.
[I 2022-07-07 22:34:06,398] Trial 5 finished with value: 0.4145336863

[I 2022-07-07 22:34:16,587] Trial 41 finished with value: 0.4127684613121506 and parameters: {'C': 116.1802681274146, 'max_iter': 150.0}. Best is trial 11 with value: 0.4162989114445425.
[I 2022-07-07 22:34:16,773] Trial 42 finished with value: 0.4148278905560459 and parameters: {'C': 174.76048927465303, 'max_iter': 100.0}. Best is trial 11 with value: 0.4162989114445425.
[I 2022-07-07 22:34:16,905] Trial 43 finished with value: 0.4145336863783466 and parameters: {'C': 334.439263306567, 'max_iter': 50.0}. Best is trial 11 with value: 0.4162989114445425.
[I 2022-07-07 22:34:17,223] Trial 44 finished with value: 0.4127684613121506 and parameters: {'C': 935.2623496248435, 'max_iter': 200.0}. Best is trial 11 with value: 0.4162989114445425.
[I 2022-07-07 22:34:17,400] Trial 45 finished with value: 0.41541629891144455 and parameters: {'C': 192.22468038438726, 'max_iter': 100.0}. Best is trial 11 with value: 0.4162989114445425.
[I 2022-07-07 22:34:17,711] Trial 46 finished with value: 0.4151

[I 2022-07-07 22:34:28,216] Trial 82 finished with value: 0.4177699323330391 and parameters: {'C': 5024.487171468417, 'max_iter': 50.0}. Best is trial 82 with value: 0.4177699323330391.
[I 2022-07-07 22:34:28,335] Trial 83 finished with value: 0.41394527802294795 and parameters: {'C': 478.76121609116996, 'max_iter': 50.0}. Best is trial 82 with value: 0.4177699323330391.
[I 2022-07-07 22:34:28,459] Trial 84 finished with value: 0.41541629891144455 and parameters: {'C': 4875.414068474475, 'max_iter': 50.0}. Best is trial 82 with value: 0.4177699323330391.
[I 2022-07-07 22:34:28,722] Trial 85 finished with value: 0.41571050308914387 and parameters: {'C': 124.26725611176869, 'max_iter': 150.0}. Best is trial 82 with value: 0.4177699323330391.
[I 2022-07-07 22:34:28,910] Trial 86 finished with value: 0.4145336863783466 and parameters: {'C': 2557.313722338783, 'max_iter': 100.0}. Best is trial 82 with value: 0.4177699323330391.
[I 2022-07-07 22:34:29,114] Trial 87 finished with value: 0.413

In [93]:
print(f"Best Value: {study.best_trial.value}")
print(f"Best Params: {study.best_params}")

Best Value: 0.4177699323330391
Best Params: {'C': 5024.487171468417, 'max_iter': 50.0}


In [94]:
kwargs = study.best_params

In [95]:
nbsvm = NBSVM(**kwargs)
nbsvm.fit(x_train_csr, y_train)
y_pred = nbsvm.predict(x_test_csr)
y_true = y_test

### Random 5

In [ ]:
#example training
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
#[None, 'micro', 'macro', 'weighted'].
print(confusion_matrix(y_true,y_pred))
print(classification_report(y_true,y_pred))
print("Precision: ",precision_score(y_true, y_pred, average="macro"))
print("Recall: ",recall_score(y_true, y_pred, average="macro"))
print("F1: ",f1_score(y_true, y_pred,  average="macro"))
print("Accuracy: ",accuracy_score(y_true, y_pred))

In [62]:
#### ROC-AUC

from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder(handle_unknown='ignore')
y_pred_roc = enc.fit_transform(np.array(y_pred).reshape(-1,1))
Y_pred = y_pred_roc.toarray()

y_true_r = enc.fit_transform(np.array(y_true).reshape(-1,1))
y_true_roc = y_true_r.toarray()

from sklearn.metrics import roc_auc_score
roc_auc_score(y_true_roc,Y_pred, multi_class='ovr')

0.8140490064421018

### Pengujian random 15

In [71]:
#example training
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
#[None, 'micro', 'macro', 'weighted'].
print(confusion_matrix(y_true,y_pred))
print(classification_report(y_true,y_pred))
print("Precision: ",precision_score(y_true, y_pred, average="macro"))
print("Recall: ",recall_score(y_true, y_pred, average="macro"))
print("F1: ",f1_score(y_true, y_pred,  average="macro"))
print("Accuracy: ",accuracy_score(y_true, y_pred))

[[1748  128   51]
 [ 131 1224   19]
 [  41   18   39]]
              precision    recall  f1-score   support

        -1.0       0.91      0.91      0.91      1927
         0.0       0.89      0.89      0.89      1374
         1.0       0.36      0.40      0.38        98

    accuracy                           0.89      3399
   macro avg       0.72      0.73      0.73      3399
weighted avg       0.89      0.89      0.89      3399

Precision:  0.720548496246196
Recall:  0.7319661248744982
F1:  0.7258999822900893
Accuracy:  0.8858487790526626


In [72]:
#### ROC-AUC

from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder(handle_unknown='ignore')
y_pred_roc = enc.fit_transform(np.array(y_pred).reshape(-1,1))
Y_pred = y_pred_roc.toarray()

y_true_r = enc.fit_transform(np.array(y_true).reshape(-1,1))
y_true_roc = y_true_r.toarray()

from sklearn.metrics import roc_auc_score
roc_auc_score(y_true_roc,Y_pred, multi_class='ovr')

0.8309576813100956

### Pengujian random 25

In [81]:
#example training
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
#[None, 'micro', 'macro', 'weighted'].
print(confusion_matrix(y_true,y_pred))
print(classification_report(y_true,y_pred))
print("Precision: ",precision_score(y_true, y_pred, average="macro"))
print("Recall: ",recall_score(y_true, y_pred, average="macro"))
print("F1: ",f1_score(y_true, y_pred,  average="macro"))
print("Accuracy: ",accuracy_score(y_true, y_pred))

[[1767  114   48]
 [ 102 1260   13]
 [  47   12   36]]
              precision    recall  f1-score   support

        -1.0       0.92      0.92      0.92      1929
         0.0       0.91      0.92      0.91      1375
         1.0       0.37      0.38      0.37        95

    accuracy                           0.90      3399
   macro avg       0.73      0.74      0.74      3399
weighted avg       0.90      0.90      0.90      3399

Precision:  0.7341529167229187
Recall:  0.7371098891013763
F1:  0.7356095066477204
Accuracy:  0.9011473962930273


In [82]:
#### ROC-AUC

from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder(handle_unknown='ignore')
y_pred_roc = enc.fit_transform(np.array(y_pred).reshape(-1,1))
Y_pred = y_pred_roc.toarray()

y_true_r = enc.fit_transform(np.array(y_true).reshape(-1,1))
y_true_roc = y_true_r.toarray()

from sklearn.metrics import roc_auc_score
roc_auc_score(y_true_roc,Y_pred, multi_class='ovr')

0.8382089481543181

### Pengujian random 35

In [38]:
#example training
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
#[None, 'micro', 'macro', 'weighted'].
print(confusion_matrix(y_true,y_pred))
print(classification_report(y_true,y_pred))
print("Precision: ",precision_score(y_true, y_pred, average="macro"))
print("Recall: ",recall_score(y_true, y_pred, average="macro"))
print("F1: ",f1_score(y_true, y_pred,  average="macro"))
print("Accuracy: ",accuracy_score(y_true, y_pred))

[[1750  143   56]
 [ 123 1223   11]
 [  47   10   36]]
              precision    recall  f1-score   support

        -1.0       0.91      0.90      0.90      1949
         0.0       0.89      0.90      0.89      1357
         1.0       0.35      0.39      0.37        93

    accuracy                           0.89      3399
   macro avg       0.72      0.73      0.72      3399
weighted avg       0.89      0.89      0.89      3399

Precision:  0.7165936786583377
Recall:  0.728748631582847
F1:  0.7223202169386426
Accuracy:  0.8852603706972639


In [40]:
#### ROC-AUC

from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder(handle_unknown='ignore')
y_pred_roc = enc.fit_transform(np.array(y_pred).reshape(-1,1))
Y_pred = y_pred_roc.toarray()

y_true_r = enc.fit_transform(np.array(y_true).reshape(-1,1))
y_true_roc = y_true_r.toarray()

from sklearn.metrics import roc_auc_score
roc_auc_score(y_true_roc,Y_pred, multi_class='ovr')

0.8289686316891304

### random 45

In [20]:
#example training
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
#[None, 'micro', 'macro', 'weighted'].
print(confusion_matrix(y_true,y_pred))
print(classification_report(y_true,y_pred))
print("Precision: ",precision_score(y_true, y_pred, average="macro"))
print("Recall: ",recall_score(y_true, y_pred, average="macro"))
print("F1: ",f1_score(y_true, y_pred,  average="macro"))
print("Accuracy: ",accuracy_score(y_true, y_pred))

[[1747  142   53]
 [ 134 1206   14]
 [  45   18   40]]
              precision    recall  f1-score   support

        -1.0       0.91      0.90      0.90      1942
         0.0       0.88      0.89      0.89      1354
         1.0       0.37      0.39      0.38       103

    accuracy                           0.88      3399
   macro avg       0.72      0.73      0.72      3399
weighted avg       0.88      0.88      0.88      3399

Precision:  0.721254245036076
Recall:  0.7262106024690448
F1:  0.7236754301858627
Accuracy:  0.8805531038540747


### GaussianNB

In [30]:
from sklearn.naive_bayes import GaussianNB

modelNB = GaussianNB()
modelNB.fit(x_train,y_train)
NB_predict = modelNB.predict(x_test)

### Random 5

In [31]:
#example training
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
#[None, 'micro', 'macro', 'weighted'].
print(confusion_matrix(y_true,NB_predict))
print(classification_report(y_true,NB_predict))
print("Precision: ",precision_score(y_true,NB_predict, average="macro"))
print("Recall: ",recall_score(y_true, NB_predict, average="macro"))
print("F1: ",f1_score(y_true,NB_predict,  average="macro"))
print("Accuracy: ",accuracy_score(y_true, NB_predict))

[[655 620 654]
 [499 424 452]
 [ 35  27  33]]
              precision    recall  f1-score   support

        -1.0       0.55      0.34      0.42      1929
         0.0       0.40      0.31      0.35      1375
         1.0       0.03      0.35      0.05        95

    accuracy                           0.33      3399
   macro avg       0.33      0.33      0.27      3399
weighted avg       0.47      0.33      0.38      3399

Precision:  0.325249189396764
Recall:  0.3317620768543254
F1:  0.2734380633301411
Accuracy:  0.32715504560164754


### Random 25

In [37]:
#example training
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
#[None, 'micro', 'macro', 'weighted'].
print(confusion_matrix(y_true,NB_predict))
print(classification_report(y_true,NB_predict))
print("Precision: ",precision_score(y_true,NB_predict, average="macro"))
print("Recall: ",recall_score(y_true, NB_predict, average="macro"))
print("F1: ",f1_score(y_true,NB_predict,  average="macro"))
print("Accuracy: ",accuracy_score(y_true, NB_predict))

[[655 620 654]
 [499 424 452]
 [ 35  27  33]]
              precision    recall  f1-score   support

        -1.0       0.55      0.34      0.42      1929
         0.0       0.40      0.31      0.35      1375
         1.0       0.03      0.35      0.05        95

    accuracy                           0.33      3399
   macro avg       0.33      0.33      0.27      3399
weighted avg       0.47      0.33      0.38      3399

Precision:  0.325249189396764
Recall:  0.3317620768543254
F1:  0.2734380633301411
Accuracy:  0.32715504560164754
