In [1]:
import pandas as pd
import numpy as np
import ast
import re
import sklearn
import six
from abc import ABCMeta
from sklearn.base import BaseEstimator, ClassifierMixin
from sklearn.utils.extmath import safe_sparse_dot
from scipy import sparse
import warnings
warnings.filterwarnings('ignore')
import nltk
import six
import re
import gensim

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import LinearSVC
from abc import ABCMeta
from sklearn.pipeline import Pipeline
from sklearn.utils import check_X_y, check_array
from scipy import sparse
from nltk.stem import PorterStemmer,WordNetLemmatizer
from scipy.sparse import issparse
from sklearn.base import BaseEstimator, ClassifierMixin
from sklearn.utils.extmath import safe_sparse_dot
from sklearn.preprocessing import normalize, binarize, LabelBinarizer
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer,TfidfTransformer
from sklearn.utils import resample
from sklearn.metrics import accuracy_score,f1_score

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
tsel = pd.read_csv(r'/content/drive/MyDrive/TA/Prepro_Sinyal.csv', usecols=['Username','Text','Sinyal','text_result'])
tsel

Username                                               Text  \
0      satriafakhri_id  @yamasaiyaa untuk masalah hp lapor aja ke yg b...   
1          Piyuuuuu21_  @bertanyarl Gatau, akhir akhir ini Telkomsel l...   
2          hypersex_pr            Ada kendala kah dengan sinyal telkomsel   
3          snwyscrtimh  @squidwardpemala @Cutimut3 @reihanahsan @sonde...   
4           aninadhany  @Telkomsel min, dari kmrn aplikasi my telkomse...   
...                ...                                                ...   
16986          Syaeeef  Sinyal mines, #sinyal #telkomsel #byu.id tolon...   
16987           abdr40  @Telkomsel ini My Telkomsel gangguan sampe kap...   
16988     thepinediary  yaallah nambah2i gawean waeee esuk2 kudu neng ...   
16989       yudaamaraa  @Telkomsel min sinyal telkomsel di rumah saya ...   
16990        ytojerxhi  @convomf tante nya sender pke nomor apa? kl Te...   

       Sinyal                                        text_result  
0         0.0  ['handphone', 'lapor', 'wajib', 'bantu', 'laca...  
1        -1.0  ['tidak tahu', 'telkomsel', 'lambat', 'kuota',...  
2        -1.0                 ['kendala', 'sinyal', 'telkomsel']  
3         0.0  ['tidak bisa', 'nomor', 'mati', 'dihidupakan',...  
4         0.0  ['admin', 'kemarin', 'aplikasi', 'punya', 'tel...  
...       ...                                                ...  
16986    -1.0  ['sinyal', 'minus', 'tolong', 'baik', 'problem...  
16987    -1.0  ['punya', 'telkomsel', 'ganggu', 'aduh', 'desa...  
16988     0.0  ['allah', 'tambah', 'kerja', 'esuk', 'neng', '...  
16989    -1.0  ['admin', 'sinyal', 'telkomsel', 'rumah', 'dae...  
16990     0.0  ['tante', 'kirim', 'pakai', 'nomor', 'telkomse...  

[16991 rows x 4 columns]

In [4]:
tsel['text_result'] = tsel['text_result'].apply(str)

In [5]:
import ast

def join_text_list(text):
    texts = ast.literal_eval(text)
    return ' '.join([text for text in texts])

tsel['text_result'] = tsel['text_result'].apply(join_text_list)
tsel

Username                                               Text  \
0      satriafakhri_id  @yamasaiyaa untuk masalah hp lapor aja ke yg b...   
1          Piyuuuuu21_  @bertanyarl Gatau, akhir akhir ini Telkomsel l...   
2          hypersex_pr            Ada kendala kah dengan sinyal telkomsel   
3          snwyscrtimh  @squidwardpemala @Cutimut3 @reihanahsan @sonde...   
4           aninadhany  @Telkomsel min, dari kmrn aplikasi my telkomse...   
...                ...                                                ...   
16986          Syaeeef  Sinyal mines, #sinyal #telkomsel #byu.id tolon...   
16987           abdr40  @Telkomsel ini My Telkomsel gangguan sampe kap...   
16988     thepinediary  yaallah nambah2i gawean waeee esuk2 kudu neng ...   
16989       yudaamaraa  @Telkomsel min sinyal telkomsel di rumah saya ...   
16990        ytojerxhi  @convomf tante nya sender pke nomor apa? kl Te...   

       Sinyal                                        text_result  
0         0.0  handphone lapor wajib bantu lacak imei perihal...  
1        -1.0  tidak tahu telkomsel lambat kuota promo murah ...  
2        -1.0                           kendala sinyal telkomsel  
3         0.0  tidak bisa nomor mati dihidupakan grapari nomo...  
4         0.0  admin kemarin aplikasi punya telkomsel ganggu ...  
...       ...                                                ...  
16986    -1.0  sinyal minus tolong baik problem location cama...  
16987    -1.0            punya telkomsel ganggu aduh desak pakai  
16988     0.0               allah tambah kerja esuk neng grapari  
16989    -1.0  admin sinyal telkomsel rumah daerah rawabunga ...  
16990     0.0  tante kirim pakai nomor telkomsel langsung gra...  

[16991 rows x 4 columns]

## Ektraksi Fitur TF-IDF 

In [6]:
%%time
# Creating the sklearn object
tfidf = sklearn.feature_extraction.text.TfidfVectorizer(ngram_range=(1, 2), max_features=1000)

# Transforming our 'tokens' column into a TF-IDF matrix and then a data frame
tfidf_df = pd.DataFrame(tfidf.fit_transform(tsel['text_result']).toarray(), 
                        columns=tfidf.get_feature_names())

CPU times: user 504 ms, sys: 76.7 ms, total: 581 ms
Wall time: 589 ms


In [7]:
tfidf_df

ada     admin  admin aplikasi  admin beli  admin grapari  admin jaring  \
0      0.0  0.000000             0.0         0.0            0.0           0.0   
1      0.0  0.000000             0.0         0.0            0.0           0.0   
2      0.0  0.000000             0.0         0.0            0.0           0.0   
3      0.0  0.000000             0.0         0.0            0.0           0.0   
4      0.0  0.179169             0.0         0.0            0.0           0.0   
...    ...       ...             ...         ...            ...           ...   
16986  0.0  0.000000             0.0         0.0            0.0           0.0   
16987  0.0  0.000000             0.0         0.0            0.0           0.0   
16988  0.0  0.000000             0.0         0.0            0.0           0.0   
16989  0.0  0.200917             0.0         0.0            0.0           0.0   
16990  0.0  0.000000             0.0         0.0            0.0           0.0   

       admin nomor  admin sinyal  admin telkomsel  admin tolong  ...  yaa  \
0              0.0      0.000000              0.0           0.0  ...  0.0   
1              0.0      0.000000              0.0           0.0  ...  0.0   
2              0.0      0.000000              0.0           0.0  ...  0.0   
3              0.0      0.000000              0.0           0.0  ...  0.0   
4              0.0      0.000000              0.0           0.0  ...  0.0   
...            ...           ...              ...           ...  ...  ...   
16986          0.0      0.000000              0.0           0.0  ...  0.0   
16987          0.0      0.000000              0.0           0.0  ...  0.0   
16988          0.0      0.000000              0.0           0.0  ...  0.0   
16989          0.0      0.349052              0.0           0.0  ...  0.0   
16990          0.0      0.000000              0.0           0.0  ...  0.0   

       yaaa  yasudah   yo  youtube  yth  yth paket  zaman  zoom  zoom pro  
0       0.0      0.0  0.0      0.0  0.0        0.0    0.0   0.0       0.0  
1       0.0      0.0  0.0      0.0  0.0        0.0    0.0   0.0       0.0  
2       0.0      0.0  0.0      0.0  0.0        0.0    0.0   0.0       0.0  
3       0.0      0.0  0.0      0.0  0.0        0.0    0.0   0.0       0.0  
4       0.0      0.0  0.0      0.0  0.0        0.0    0.0   0.0       0.0  
...     ...      ...  ...      ...  ...        ...    ...   ...       ...  
16986   0.0      0.0  0.0      0.0  0.0        0.0    0.0   0.0       0.0  
16987   0.0      0.0  0.0      0.0  0.0        0.0    0.0   0.0       0.0  
16988   0.0      0.0  0.0      0.0  0.0        0.0    0.0   0.0       0.0  
16989   0.0      0.0  0.0      0.0  0.0        0.0    0.0   0.0       0.0  
16990   0.0      0.0  0.0      0.0  0.0        0.0    0.0   0.0       0.0  

[16991 rows x 1000 columns]

In [8]:
tfidf_vectors = tfidf.fit_transform(tsel['text_result'])

In [9]:
vect_score = np.asarray(tfidf_vectors.mean(axis=0)).ravel().tolist()
tsel_weight = pd.DataFrame({'term': tfidf.get_feature_names(), 'weight': vect_score})
tsel_weight.sort_values(by='weight',ascending=False,inplace=True)
tsel_weight.reset_index(inplace=True)
tsel_weight.drop(['index'], axis='columns', inplace=True)
tsel_weight.head()

term    weight
0  telkomsel  0.102464
1     lambat  0.067736
2     sinyal  0.064047
3     jaring  0.057322
4    grapari  0.056099

In [10]:
tfidf_vec = tfidf_df.copy()

In [11]:
tsel['Sinyal'].value_counts()

-1.0    9643
 0.0    6877
 1.0     471
Name: Sinyal, dtype: int64

In [12]:
X = tfidf_vec
y = tsel['Sinyal']


In [13]:
tsel.iloc[3577]

Username                                                 ggummyn
Text           Aduh.. sinyal Telkomsel please be nice. Jangan...
Sinyal                                                      -1.0
text_result    aduh sinyal telkomsel tolong be ganggu malam m...
Name: 3577, dtype: object

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y, test_size=0.2, random_state=25)

## Klasifikasi MNB

In [15]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()

# params_mnb = {'alpha': [0.1],
#               'fit_prior': [True, False]}

In [16]:
# from sklearn.model_selection import GridSearchCV
# clf = GridSearchCV(model, params_mnb, cv=10)
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
y_true = y_test

### random 25

In [17]:
#example training
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
#[None, 'micro', 'macro', 'weighted'].
print(confusion_matrix(y_true,y_pred))
print(classification_report(y_true,y_pred))
print("Precision: ",precision_score(y_true, y_pred, average="macro"))
print("Recall: ",recall_score(y_true, y_pred, average="macro"))
print("F1: ",f1_score(y_true, y_pred,  average="macro"))
print("Accuracy: ",accuracy_score(y_true, y_pred))

[[1859   70    0]
 [ 106 1264    5]
 [  80    6    9]]
              precision    recall  f1-score   support

        -1.0       0.91      0.96      0.94      1929
         0.0       0.94      0.92      0.93      1375
         1.0       0.64      0.09      0.17        95

    accuracy                           0.92      3399
   macro avg       0.83      0.66      0.68      3399
weighted avg       0.92      0.92      0.91      3399

Precision:  0.831729059904807
Recall:  0.6592404457111013
F1:  0.6772807605232866
Accuracy:  0.9214474845542807


In [18]:
#### ROC-AUC

from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder(handle_unknown='ignore')
y_pred_roc = enc.fit_transform(np.array(y_pred).reshape(-1,1))
Y_pred = y_pred_roc.toarray()

y_true_r = enc.fit_transform(np.array(y_true).reshape(-1,1))
y_true_roc = y_true_r.toarray()

from sklearn.metrics import roc_auc_score
roc_auc_score(y_true_roc,Y_pred, multi_class='ovr')

0.8020213334304164