In [5]:
import pandas as pd
import numpy as np
import ast
import re
import sklearn
import six
from abc import ABCMeta
from sklearn.base import BaseEstimator, ClassifierMixin
from sklearn.utils.extmath import safe_sparse_dot
from scipy import sparse
import warnings
warnings.filterwarnings('ignore')
import nltk
import six
import re
import gensim

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import LinearSVC
from abc import ABCMeta
from sklearn.pipeline import Pipeline
from sklearn.utils import check_X_y, check_array
from scipy import sparse
from nltk.stem import PorterStemmer,WordNetLemmatizer
from scipy.sparse import issparse
from sklearn.base import BaseEstimator, ClassifierMixin
from sklearn.utils.extmath import safe_sparse_dot
from sklearn.preprocessing import normalize, binarize, LabelBinarizer
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer,TfidfTransformer
from sklearn.utils import resample
from sklearn.metrics import accuracy_score,f1_score

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [7]:
tsel = pd.read_csv(r'/content/drive/MyDrive/TA/Prepro_Pelayanan.csv', usecols=['Username','Text','Pelayanan','text_result'])
tsel

Username                                               Text  \
0      satriafakhri_id  @yamasaiyaa untuk masalah hp lapor aja ke yg b...   
1          Piyuuuuu21_  @bertanyarl Gatau, akhir akhir ini Telkomsel l...   
2          hypersex_pr            Ada kendala kah dengan sinyal telkomsel   
3          snwyscrtimh  @squidwardpemala @Cutimut3 @reihanahsan @sonde...   
4           aninadhany  @Telkomsel min, dari kmrn aplikasi my telkomse...   
...                ...                                                ...   
16986          Syaeeef  Sinyal mines, #sinyal #telkomsel #byu.id tolon...   
16987           abdr40  @Telkomsel ini My Telkomsel gangguan sampe kap...   
16988     thepinediary  yaallah nambah2i gawean waeee esuk2 kudu neng ...   
16989       yudaamaraa  @Telkomsel min sinyal telkomsel di rumah saya ...   
16990        ytojerxhi  @convomf tante nya sender pke nomor apa? kl Te...   

       Pelayanan                                        text_result  
0            0.0  ['handphone', 'lapor', 'wajib', 'bantu', 'laca...  
1            0.0  ['tidak tahu', 'telkomsel', 'lambat', 'kuota',...  
2            0.0                 ['kendala', 'sinyal', 'telkomsel']  
3           -1.0  ['tidak bisa', 'nomor', 'mati', 'dihidupakan',...  
4           -1.0  ['admin', 'kemarin', 'aplikasi', 'punya', 'tel...  
...          ...                                                ...  
16986        0.0  ['sinyal', 'minus', 'tolong', 'baik', 'problem...  
16987        0.0  ['punya', 'telkomsel', 'ganggu', 'aduh', 'desa...  
16988        0.0  ['allah', 'tambah', 'kerja', 'esuk', 'neng', '...  
16989        0.0  ['admin', 'sinyal', 'telkomsel', 'rumah', 'dae...  
16990        0.0  ['tante', 'kirim', 'pakai', 'nomor', 'telkomse...  

[16991 rows x 4 columns]

In [8]:
tsel['text_result'] = tsel['text_result'].apply(str)

In [9]:
import ast

def join_text_list(text):
    texts = ast.literal_eval(text)
    return ' '.join([text for text in texts])

tsel['text_result'] = tsel['text_result'].apply(join_text_list)
tsel

Username                                               Text  \
0      satriafakhri_id  @yamasaiyaa untuk masalah hp lapor aja ke yg b...   
1          Piyuuuuu21_  @bertanyarl Gatau, akhir akhir ini Telkomsel l...   
2          hypersex_pr            Ada kendala kah dengan sinyal telkomsel   
3          snwyscrtimh  @squidwardpemala @Cutimut3 @reihanahsan @sonde...   
4           aninadhany  @Telkomsel min, dari kmrn aplikasi my telkomse...   
...                ...                                                ...   
16986          Syaeeef  Sinyal mines, #sinyal #telkomsel #byu.id tolon...   
16987           abdr40  @Telkomsel ini My Telkomsel gangguan sampe kap...   
16988     thepinediary  yaallah nambah2i gawean waeee esuk2 kudu neng ...   
16989       yudaamaraa  @Telkomsel min sinyal telkomsel di rumah saya ...   
16990        ytojerxhi  @convomf tante nya sender pke nomor apa? kl Te...   

       Pelayanan                                        text_result  
0            0.0  handphone lapor wajib bantu lacak imei perihal...  
1            0.0  tidak tahu telkomsel lambat kuota promo murah ...  
2            0.0                           kendala sinyal telkomsel  
3           -1.0  tidak bisa nomor mati dihidupakan grapari nomo...  
4           -1.0  admin kemarin aplikasi punya telkomsel ganggu ...  
...          ...                                                ...  
16986        0.0  sinyal minus tolong baik problem location cama...  
16987        0.0            punya telkomsel ganggu aduh desak pakai  
16988        0.0               allah tambah kerja esuk neng grapari  
16989        0.0  admin sinyal telkomsel rumah daerah rawabunga ...  
16990        0.0  tante kirim pakai nomor telkomsel langsung gra...  

[16991 rows x 4 columns]

## Ektraksi Fitur TF-IDF 

In [10]:
%%time
# Creating the sklearn object
tfidf = sklearn.feature_extraction.text.TfidfVectorizer(ngram_range=(1, 2), max_features=1000)

# Transforming our 'tokens' column into a TF-IDF matrix and then a data frame
tfidf_df = pd.DataFrame(tfidf.fit_transform(tsel['text_result']).toarray(), 
                        columns=tfidf.get_feature_names())

CPU times: user 555 ms, sys: 75.1 ms, total: 630 ms
Wall time: 648 ms


In [11]:
tfidf_df

ada     admin  admin aplikasi  admin beli  admin grapari  admin jaring  \
0      0.0  0.000000             0.0         0.0            0.0           0.0   
1      0.0  0.000000             0.0         0.0            0.0           0.0   
2      0.0  0.000000             0.0         0.0            0.0           0.0   
3      0.0  0.000000             0.0         0.0            0.0           0.0   
4      0.0  0.179169             0.0         0.0            0.0           0.0   
...    ...       ...             ...         ...            ...           ...   
16986  0.0  0.000000             0.0         0.0            0.0           0.0   
16987  0.0  0.000000             0.0         0.0            0.0           0.0   
16988  0.0  0.000000             0.0         0.0            0.0           0.0   
16989  0.0  0.200917             0.0         0.0            0.0           0.0   
16990  0.0  0.000000             0.0         0.0            0.0           0.0   

       admin nomor  admin sinyal  admin telkomsel  admin tolong  ...  yaa  \
0              0.0      0.000000              0.0           0.0  ...  0.0   
1              0.0      0.000000              0.0           0.0  ...  0.0   
2              0.0      0.000000              0.0           0.0  ...  0.0   
3              0.0      0.000000              0.0           0.0  ...  0.0   
4              0.0      0.000000              0.0           0.0  ...  0.0   
...            ...           ...              ...           ...  ...  ...   
16986          0.0      0.000000              0.0           0.0  ...  0.0   
16987          0.0      0.000000              0.0           0.0  ...  0.0   
16988          0.0      0.000000              0.0           0.0  ...  0.0   
16989          0.0      0.349052              0.0           0.0  ...  0.0   
16990          0.0      0.000000              0.0           0.0  ...  0.0   

       yaaa  yasudah   yo  youtube  yth  yth paket  zaman  zoom  zoom pro  
0       0.0      0.0  0.0      0.0  0.0        0.0    0.0   0.0       0.0  
1       0.0      0.0  0.0      0.0  0.0        0.0    0.0   0.0       0.0  
2       0.0      0.0  0.0      0.0  0.0        0.0    0.0   0.0       0.0  
3       0.0      0.0  0.0      0.0  0.0        0.0    0.0   0.0       0.0  
4       0.0      0.0  0.0      0.0  0.0        0.0    0.0   0.0       0.0  
...     ...      ...  ...      ...  ...        ...    ...   ...       ...  
16986   0.0      0.0  0.0      0.0  0.0        0.0    0.0   0.0       0.0  
16987   0.0      0.0  0.0      0.0  0.0        0.0    0.0   0.0       0.0  
16988   0.0      0.0  0.0      0.0  0.0        0.0    0.0   0.0       0.0  
16989   0.0      0.0  0.0      0.0  0.0        0.0    0.0   0.0       0.0  
16990   0.0      0.0  0.0      0.0  0.0        0.0    0.0   0.0       0.0  

[16991 rows x 1000 columns]

In [12]:
tfidf_vectors = tfidf.fit_transform(tsel['text_result'])

In [13]:
vect_score = np.asarray(tfidf_vectors.mean(axis=0)).ravel().tolist()
tsel_weight = pd.DataFrame({'term': tfidf.get_feature_names(), 'weight': vect_score})
tsel_weight.sort_values(by='weight',ascending=False,inplace=True)
tsel_weight.reset_index(inplace=True)
tsel_weight.drop(['index'], axis='columns', inplace=True)
tsel_weight.head()

term    weight
0  telkomsel  0.102464
1     lambat  0.067736
2     sinyal  0.064047
3     jaring  0.057322
4    grapari  0.056099

In [14]:
tfidf_vec = tfidf_df.copy()

In [15]:
tsel['Pelayanan'].value_counts()

 0.0    13548
-1.0     2225
 1.0     1218
Name: Pelayanan, dtype: int64

In [16]:
X = tfidf_vec
y = tsel['Pelayanan']


In [17]:
tsel.iloc[3577]

Username                                                 ggummyn
Text           Aduh.. sinyal Telkomsel please be nice. Jangan...
Pelayanan                                                    0.0
text_result    aduh sinyal telkomsel tolong be ganggu malam m...
Name: 3577, dtype: object

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y, test_size=0.1, random_state=5)

## Klasifikasi MNB

In [19]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()

# params_mnb = {'alpha': [0.1],
#               'fit_prior': [True, False]}

In [20]:
# from sklearn.model_selection import GridSearchCV
# clf = GridSearchCV(model, params_mnb, cv=10)
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
y_true = y_test

### random 5

In [21]:
#example training
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
#[None, 'micro', 'macro', 'weighted'].
print(confusion_matrix(y_true,y_pred))
print(classification_report(y_true,y_pred))
print("Precision: ",precision_score(y_true, y_pred, average="macro"))
print("Recall: ",recall_score(y_true, y_pred, average="macro"))
print("F1: ",f1_score(y_true, y_pred,  average="macro"))
print("Accuracy: ",accuracy_score(y_true, y_pred))

[[ 130  105   10]
 [  59 1233   19]
 [  20   70   54]]
              precision    recall  f1-score   support

        -1.0       0.62      0.53      0.57       245
         0.0       0.88      0.94      0.91      1311
         1.0       0.65      0.38      0.48       144

    accuracy                           0.83      1700
   macro avg       0.72      0.62      0.65      1700
weighted avg       0.82      0.83      0.82      1700

Precision:  0.7161074020964241
Recall:  0.6153718924640795
F1:  0.6518030782458136
Accuracy:  0.8335294117647059


#### ROC-AUC

In [22]:
#### ROC-AUC

from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder(handle_unknown='ignore')
y_pred_roc = enc.fit_transform(np.array(y_pred).reshape(-1,1))
Y_pred = y_pred_roc.toarray()

y_true_r = enc.fit_transform(np.array(y_true).reshape(-1,1))
y_true_roc = y_true_r.toarray()

from sklearn.metrics import roc_auc_score
roc_auc_score(y_true_roc,Y_pred, multi_class='ovr')

0.7205518578861474

### random 25

In [ ]:
#example training
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
#[None, 'micro', 'macro', 'weighted'].
print(confusion_matrix(y_true,y_pred))
print(classification_report(y_true,y_pred))
print("Precision: ",precision_score(y_true, y_pred, average="macro"))
print("Recall: ",recall_score(y_true, y_pred, average="macro"))
print("F1: ",f1_score(y_true, y_pred,  average="macro"))
print("Accuracy: ",accuracy_score(y_true, y_pred))

[[ 127   79    8]
 [  51 1289   31]
 [  24   48   43]]
              precision    recall  f1-score   support

        -1.0       0.63      0.59      0.61       214
         0.0       0.91      0.94      0.93      1371
         1.0       0.52      0.37      0.44       115

    accuracy                           0.86      1700
   macro avg       0.69      0.64      0.66      1700
weighted avg       0.85      0.86      0.85      1700

Precision:  0.6878046165509483
Recall:  0.6358535433333797
F1:  0.6573780388820167
Accuracy:  0.8582352941176471


In [ ]:
#example training
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
#[None, 'micro', 'macro', 'weighted'].
print(confusion_matrix(y_true,y_pred))
print(classification_report(y_true,y_pred))
print("Precision: ",precision_score(y_true, y_pred, average="macro"))
print("Recall: ",recall_score(y_true, y_pred, average="macro"))
print("F1: ",f1_score(y_true, y_pred,  average="macro"))
print("Accuracy: ",accuracy_score(y_true, y_pred))

[[ 132   97   14]
 [  41 1255   36]
 [  12   61   52]]
              precision    recall  f1-score   support

        -1.0       0.71      0.54      0.62       243
         0.0       0.89      0.94      0.91      1332
         1.0       0.51      0.42      0.46       125

    accuracy                           0.85      1700
   macro avg       0.70      0.63      0.66      1700
weighted avg       0.84      0.85      0.84      1700

Precision:  0.7038328699625066
Recall:  0.6338006895784672
F1:  0.6631206697593087
Accuracy:  0.8464705882352941
